// Workflow event types
export type WorkflowEvent =
  | { type: 'papers_added'; count: number }
  | { type: 'extraction_completed'; paperId: string; title: string; pathways: string[] }
  | { type: 'conflict_detected'; pathway: string; description: string }
  | { type: 'hypothesis_created'; statement: string }
  | { type: 'experiment_saved'; name: string; hypothesisId?: string }
  | { type: 'experiment_failed'; name: string }
  | { type: 'data_uploaded'; fileName: string }
  | { type: 'project_idle'; days: number };

// Proactive insight generated by rules
export interface ProactiveInsight {
  id: string;
  type: 'info' | 'warning' | 'suggestion';
  title: string;
  description: string;
  action?: { label: string; href: string };
  createdAt: number;
}

// Simple event bus implementation
type EventHandler = (event: WorkflowEvent) => void;

class WorkflowEventBus {
  private handlers: Map<string, Set<EventHandler>> = new Map();

  emit(event: WorkflowEvent): void {
    const handlers = this.handlers.get(event.type);
    if (handlers) {
      handlers.forEach((h) => h(event));
    }
    // Also notify wildcard listeners
    const wildcardHandlers = this.handlers.get('*');
    if (wildcardHandlers) {
      wildcardHandlers.forEach((h) => h(event));
    }
  }

  on(type: WorkflowEvent['type'] | '*', handler: EventHandler): () => void {
    if (!this.handlers.has(type)) {
      this.handlers.set(type, new Set());
    }
    this.handlers.get(type)!.add(handler);
    return () => {
      this.handlers.get(type)?.delete(handler);
    };
  }
}

export const workflowBus = new WorkflowEventBus();
