
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ExperimentData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ExperimentData
 * 
 */
export type ExperimentDataModel = runtime.Types.Result.DefaultSelection<Prisma.$ExperimentDataPayload>

export type AggregateExperimentData = {
  _count: ExperimentDataCountAggregateOutputType | null
  _min: ExperimentDataMinAggregateOutputType | null
  _max: ExperimentDataMaxAggregateOutputType | null
}

export type ExperimentDataMinAggregateOutputType = {
  id: string | null
  experimentId: string | null
  fileType: string | null
  fileName: string | null
  fileUrl: string | null
  createdAt: Date | null
}

export type ExperimentDataMaxAggregateOutputType = {
  id: string | null
  experimentId: string | null
  fileType: string | null
  fileName: string | null
  fileUrl: string | null
  createdAt: Date | null
}

export type ExperimentDataCountAggregateOutputType = {
  id: number
  experimentId: number
  fileType: number
  fileName: number
  fileUrl: number
  parsedData: number
  analysis: number
  createdAt: number
  _all: number
}


export type ExperimentDataMinAggregateInputType = {
  id?: true
  experimentId?: true
  fileType?: true
  fileName?: true
  fileUrl?: true
  createdAt?: true
}

export type ExperimentDataMaxAggregateInputType = {
  id?: true
  experimentId?: true
  fileType?: true
  fileName?: true
  fileUrl?: true
  createdAt?: true
}

export type ExperimentDataCountAggregateInputType = {
  id?: true
  experimentId?: true
  fileType?: true
  fileName?: true
  fileUrl?: true
  parsedData?: true
  analysis?: true
  createdAt?: true
  _all?: true
}

export type ExperimentDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExperimentData to aggregate.
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperimentData to fetch.
   */
  orderBy?: Prisma.ExperimentDataOrderByWithRelationInput | Prisma.ExperimentDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExperimentDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperimentData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperimentData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ExperimentData
  **/
  _count?: true | ExperimentDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExperimentDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExperimentDataMaxAggregateInputType
}

export type GetExperimentDataAggregateType<T extends ExperimentDataAggregateArgs> = {
      [P in keyof T & keyof AggregateExperimentData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExperimentData[P]>
    : Prisma.GetScalarType<T[P], AggregateExperimentData[P]>
}




export type ExperimentDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExperimentDataWhereInput
  orderBy?: Prisma.ExperimentDataOrderByWithAggregationInput | Prisma.ExperimentDataOrderByWithAggregationInput[]
  by: Prisma.ExperimentDataScalarFieldEnum[] | Prisma.ExperimentDataScalarFieldEnum
  having?: Prisma.ExperimentDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExperimentDataCountAggregateInputType | true
  _min?: ExperimentDataMinAggregateInputType
  _max?: ExperimentDataMaxAggregateInputType
}

export type ExperimentDataGroupByOutputType = {
  id: string
  experimentId: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData: runtime.JsonValue | null
  analysis: runtime.JsonValue | null
  createdAt: Date
  _count: ExperimentDataCountAggregateOutputType | null
  _min: ExperimentDataMinAggregateOutputType | null
  _max: ExperimentDataMaxAggregateOutputType | null
}

export type GetExperimentDataGroupByPayload<T extends ExperimentDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExperimentDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExperimentDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExperimentDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExperimentDataGroupByOutputType[P]>
      }
    >
  >



export type ExperimentDataWhereInput = {
  AND?: Prisma.ExperimentDataWhereInput | Prisma.ExperimentDataWhereInput[]
  OR?: Prisma.ExperimentDataWhereInput[]
  NOT?: Prisma.ExperimentDataWhereInput | Prisma.ExperimentDataWhereInput[]
  id?: Prisma.StringFilter<"ExperimentData"> | string
  experimentId?: Prisma.StringFilter<"ExperimentData"> | string
  fileType?: Prisma.StringFilter<"ExperimentData"> | string
  fileName?: Prisma.StringFilter<"ExperimentData"> | string
  fileUrl?: Prisma.StringFilter<"ExperimentData"> | string
  parsedData?: Prisma.JsonNullableFilter<"ExperimentData">
  analysis?: Prisma.JsonNullableFilter<"ExperimentData">
  createdAt?: Prisma.DateTimeFilter<"ExperimentData"> | Date | string
  experiment?: Prisma.XOR<Prisma.ExperimentScalarRelationFilter, Prisma.ExperimentWhereInput>
}

export type ExperimentDataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  experimentId?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  parsedData?: Prisma.SortOrderInput | Prisma.SortOrder
  analysis?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  experiment?: Prisma.ExperimentOrderByWithRelationInput
}

export type ExperimentDataWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ExperimentDataWhereInput | Prisma.ExperimentDataWhereInput[]
  OR?: Prisma.ExperimentDataWhereInput[]
  NOT?: Prisma.ExperimentDataWhereInput | Prisma.ExperimentDataWhereInput[]
  experimentId?: Prisma.StringFilter<"ExperimentData"> | string
  fileType?: Prisma.StringFilter<"ExperimentData"> | string
  fileName?: Prisma.StringFilter<"ExperimentData"> | string
  fileUrl?: Prisma.StringFilter<"ExperimentData"> | string
  parsedData?: Prisma.JsonNullableFilter<"ExperimentData">
  analysis?: Prisma.JsonNullableFilter<"ExperimentData">
  createdAt?: Prisma.DateTimeFilter<"ExperimentData"> | Date | string
  experiment?: Prisma.XOR<Prisma.ExperimentScalarRelationFilter, Prisma.ExperimentWhereInput>
}, "id">

export type ExperimentDataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  experimentId?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  parsedData?: Prisma.SortOrderInput | Prisma.SortOrder
  analysis?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ExperimentDataCountOrderByAggregateInput
  _max?: Prisma.ExperimentDataMaxOrderByAggregateInput
  _min?: Prisma.ExperimentDataMinOrderByAggregateInput
}

export type ExperimentDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExperimentDataScalarWhereWithAggregatesInput | Prisma.ExperimentDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExperimentDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExperimentDataScalarWhereWithAggregatesInput | Prisma.ExperimentDataScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ExperimentData"> | string
  experimentId?: Prisma.StringWithAggregatesFilter<"ExperimentData"> | string
  fileType?: Prisma.StringWithAggregatesFilter<"ExperimentData"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"ExperimentData"> | string
  fileUrl?: Prisma.StringWithAggregatesFilter<"ExperimentData"> | string
  parsedData?: Prisma.JsonNullableWithAggregatesFilter<"ExperimentData">
  analysis?: Prisma.JsonNullableWithAggregatesFilter<"ExperimentData">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ExperimentData"> | Date | string
}

export type ExperimentDataCreateInput = {
  id?: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  experiment: Prisma.ExperimentCreateNestedOneWithoutRawDataInput
}

export type ExperimentDataUncheckedCreateInput = {
  id?: string
  experimentId: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ExperimentDataUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiment?: Prisma.ExperimentUpdateOneRequiredWithoutRawDataNestedInput
}

export type ExperimentDataUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  experimentId?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExperimentDataCreateManyInput = {
  id?: string
  experimentId: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ExperimentDataUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExperimentDataUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  experimentId?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExperimentDataListRelationFilter = {
  every?: Prisma.ExperimentDataWhereInput
  some?: Prisma.ExperimentDataWhereInput
  none?: Prisma.ExperimentDataWhereInput
}

export type ExperimentDataOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExperimentDataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  experimentId?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  parsedData?: Prisma.SortOrder
  analysis?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExperimentDataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  experimentId?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExperimentDataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  experimentId?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExperimentDataCreateNestedManyWithoutExperimentInput = {
  create?: Prisma.XOR<Prisma.ExperimentDataCreateWithoutExperimentInput, Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput> | Prisma.ExperimentDataCreateWithoutExperimentInput[] | Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput[]
  connectOrCreate?: Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput | Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput[]
  createMany?: Prisma.ExperimentDataCreateManyExperimentInputEnvelope
  connect?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
}

export type ExperimentDataUncheckedCreateNestedManyWithoutExperimentInput = {
  create?: Prisma.XOR<Prisma.ExperimentDataCreateWithoutExperimentInput, Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput> | Prisma.ExperimentDataCreateWithoutExperimentInput[] | Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput[]
  connectOrCreate?: Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput | Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput[]
  createMany?: Prisma.ExperimentDataCreateManyExperimentInputEnvelope
  connect?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
}

export type ExperimentDataUpdateManyWithoutExperimentNestedInput = {
  create?: Prisma.XOR<Prisma.ExperimentDataCreateWithoutExperimentInput, Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput> | Prisma.ExperimentDataCreateWithoutExperimentInput[] | Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput[]
  connectOrCreate?: Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput | Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput[]
  upsert?: Prisma.ExperimentDataUpsertWithWhereUniqueWithoutExperimentInput | Prisma.ExperimentDataUpsertWithWhereUniqueWithoutExperimentInput[]
  createMany?: Prisma.ExperimentDataCreateManyExperimentInputEnvelope
  set?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  disconnect?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  delete?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  connect?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  update?: Prisma.ExperimentDataUpdateWithWhereUniqueWithoutExperimentInput | Prisma.ExperimentDataUpdateWithWhereUniqueWithoutExperimentInput[]
  updateMany?: Prisma.ExperimentDataUpdateManyWithWhereWithoutExperimentInput | Prisma.ExperimentDataUpdateManyWithWhereWithoutExperimentInput[]
  deleteMany?: Prisma.ExperimentDataScalarWhereInput | Prisma.ExperimentDataScalarWhereInput[]
}

export type ExperimentDataUncheckedUpdateManyWithoutExperimentNestedInput = {
  create?: Prisma.XOR<Prisma.ExperimentDataCreateWithoutExperimentInput, Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput> | Prisma.ExperimentDataCreateWithoutExperimentInput[] | Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput[]
  connectOrCreate?: Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput | Prisma.ExperimentDataCreateOrConnectWithoutExperimentInput[]
  upsert?: Prisma.ExperimentDataUpsertWithWhereUniqueWithoutExperimentInput | Prisma.ExperimentDataUpsertWithWhereUniqueWithoutExperimentInput[]
  createMany?: Prisma.ExperimentDataCreateManyExperimentInputEnvelope
  set?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  disconnect?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  delete?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  connect?: Prisma.ExperimentDataWhereUniqueInput | Prisma.ExperimentDataWhereUniqueInput[]
  update?: Prisma.ExperimentDataUpdateWithWhereUniqueWithoutExperimentInput | Prisma.ExperimentDataUpdateWithWhereUniqueWithoutExperimentInput[]
  updateMany?: Prisma.ExperimentDataUpdateManyWithWhereWithoutExperimentInput | Prisma.ExperimentDataUpdateManyWithWhereWithoutExperimentInput[]
  deleteMany?: Prisma.ExperimentDataScalarWhereInput | Prisma.ExperimentDataScalarWhereInput[]
}

export type ExperimentDataCreateWithoutExperimentInput = {
  id?: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ExperimentDataUncheckedCreateWithoutExperimentInput = {
  id?: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ExperimentDataCreateOrConnectWithoutExperimentInput = {
  where: Prisma.ExperimentDataWhereUniqueInput
  create: Prisma.XOR<Prisma.ExperimentDataCreateWithoutExperimentInput, Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput>
}

export type ExperimentDataCreateManyExperimentInputEnvelope = {
  data: Prisma.ExperimentDataCreateManyExperimentInput | Prisma.ExperimentDataCreateManyExperimentInput[]
  skipDuplicates?: boolean
}

export type ExperimentDataUpsertWithWhereUniqueWithoutExperimentInput = {
  where: Prisma.ExperimentDataWhereUniqueInput
  update: Prisma.XOR<Prisma.ExperimentDataUpdateWithoutExperimentInput, Prisma.ExperimentDataUncheckedUpdateWithoutExperimentInput>
  create: Prisma.XOR<Prisma.ExperimentDataCreateWithoutExperimentInput, Prisma.ExperimentDataUncheckedCreateWithoutExperimentInput>
}

export type ExperimentDataUpdateWithWhereUniqueWithoutExperimentInput = {
  where: Prisma.ExperimentDataWhereUniqueInput
  data: Prisma.XOR<Prisma.ExperimentDataUpdateWithoutExperimentInput, Prisma.ExperimentDataUncheckedUpdateWithoutExperimentInput>
}

export type ExperimentDataUpdateManyWithWhereWithoutExperimentInput = {
  where: Prisma.ExperimentDataScalarWhereInput
  data: Prisma.XOR<Prisma.ExperimentDataUpdateManyMutationInput, Prisma.ExperimentDataUncheckedUpdateManyWithoutExperimentInput>
}

export type ExperimentDataScalarWhereInput = {
  AND?: Prisma.ExperimentDataScalarWhereInput | Prisma.ExperimentDataScalarWhereInput[]
  OR?: Prisma.ExperimentDataScalarWhereInput[]
  NOT?: Prisma.ExperimentDataScalarWhereInput | Prisma.ExperimentDataScalarWhereInput[]
  id?: Prisma.StringFilter<"ExperimentData"> | string
  experimentId?: Prisma.StringFilter<"ExperimentData"> | string
  fileType?: Prisma.StringFilter<"ExperimentData"> | string
  fileName?: Prisma.StringFilter<"ExperimentData"> | string
  fileUrl?: Prisma.StringFilter<"ExperimentData"> | string
  parsedData?: Prisma.JsonNullableFilter<"ExperimentData">
  analysis?: Prisma.JsonNullableFilter<"ExperimentData">
  createdAt?: Prisma.DateTimeFilter<"ExperimentData"> | Date | string
}

export type ExperimentDataCreateManyExperimentInput = {
  id?: string
  fileType: string
  fileName: string
  fileUrl: string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ExperimentDataUpdateWithoutExperimentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExperimentDataUncheckedUpdateWithoutExperimentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExperimentDataUncheckedUpdateManyWithoutExperimentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  parsedData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  analysis?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ExperimentDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  experimentId?: boolean
  fileType?: boolean
  fileName?: boolean
  fileUrl?: boolean
  parsedData?: boolean
  analysis?: boolean
  createdAt?: boolean
  experiment?: boolean | Prisma.ExperimentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["experimentData"]>

export type ExperimentDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  experimentId?: boolean
  fileType?: boolean
  fileName?: boolean
  fileUrl?: boolean
  parsedData?: boolean
  analysis?: boolean
  createdAt?: boolean
  experiment?: boolean | Prisma.ExperimentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["experimentData"]>

export type ExperimentDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  experimentId?: boolean
  fileType?: boolean
  fileName?: boolean
  fileUrl?: boolean
  parsedData?: boolean
  analysis?: boolean
  createdAt?: boolean
  experiment?: boolean | Prisma.ExperimentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["experimentData"]>

export type ExperimentDataSelectScalar = {
  id?: boolean
  experimentId?: boolean
  fileType?: boolean
  fileName?: boolean
  fileUrl?: boolean
  parsedData?: boolean
  analysis?: boolean
  createdAt?: boolean
}

export type ExperimentDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "experimentId" | "fileType" | "fileName" | "fileUrl" | "parsedData" | "analysis" | "createdAt", ExtArgs["result"]["experimentData"]>
export type ExperimentDataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experiment?: boolean | Prisma.ExperimentDefaultArgs<ExtArgs>
}
export type ExperimentDataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experiment?: boolean | Prisma.ExperimentDefaultArgs<ExtArgs>
}
export type ExperimentDataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experiment?: boolean | Prisma.ExperimentDefaultArgs<ExtArgs>
}

export type $ExperimentDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ExperimentData"
  objects: {
    experiment: Prisma.$ExperimentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    experimentId: string
    fileType: string
    fileName: string
    fileUrl: string
    parsedData: runtime.JsonValue | null
    analysis: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["experimentData"]>
  composites: {}
}

export type ExperimentDataGetPayload<S extends boolean | null | undefined | ExperimentDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload, S>

export type ExperimentDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExperimentDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExperimentDataCountAggregateInputType | true
  }

export interface ExperimentDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ExperimentData'], meta: { name: 'ExperimentData' } }
  /**
   * Find zero or one ExperimentData that matches the filter.
   * @param {ExperimentDataFindUniqueArgs} args - Arguments to find a ExperimentData
   * @example
   * // Get one ExperimentData
   * const experimentData = await prisma.experimentData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExperimentDataFindUniqueArgs>(args: Prisma.SelectSubset<T, ExperimentDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ExperimentData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExperimentDataFindUniqueOrThrowArgs} args - Arguments to find a ExperimentData
   * @example
   * // Get one ExperimentData
   * const experimentData = await prisma.experimentData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExperimentDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExperimentDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExperimentData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataFindFirstArgs} args - Arguments to find a ExperimentData
   * @example
   * // Get one ExperimentData
   * const experimentData = await prisma.experimentData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExperimentDataFindFirstArgs>(args?: Prisma.SelectSubset<T, ExperimentDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExperimentData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataFindFirstOrThrowArgs} args - Arguments to find a ExperimentData
   * @example
   * // Get one ExperimentData
   * const experimentData = await prisma.experimentData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExperimentDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExperimentDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ExperimentData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExperimentData
   * const experimentData = await prisma.experimentData.findMany()
   * 
   * // Get first 10 ExperimentData
   * const experimentData = await prisma.experimentData.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const experimentDataWithIdOnly = await prisma.experimentData.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExperimentDataFindManyArgs>(args?: Prisma.SelectSubset<T, ExperimentDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ExperimentData.
   * @param {ExperimentDataCreateArgs} args - Arguments to create a ExperimentData.
   * @example
   * // Create one ExperimentData
   * const ExperimentData = await prisma.experimentData.create({
   *   data: {
   *     // ... data to create a ExperimentData
   *   }
   * })
   * 
   */
  create<T extends ExperimentDataCreateArgs>(args: Prisma.SelectSubset<T, ExperimentDataCreateArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ExperimentData.
   * @param {ExperimentDataCreateManyArgs} args - Arguments to create many ExperimentData.
   * @example
   * // Create many ExperimentData
   * const experimentData = await prisma.experimentData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExperimentDataCreateManyArgs>(args?: Prisma.SelectSubset<T, ExperimentDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExperimentData and returns the data saved in the database.
   * @param {ExperimentDataCreateManyAndReturnArgs} args - Arguments to create many ExperimentData.
   * @example
   * // Create many ExperimentData
   * const experimentData = await prisma.experimentData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ExperimentData and only return the `id`
   * const experimentDataWithIdOnly = await prisma.experimentData.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExperimentDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExperimentDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ExperimentData.
   * @param {ExperimentDataDeleteArgs} args - Arguments to delete one ExperimentData.
   * @example
   * // Delete one ExperimentData
   * const ExperimentData = await prisma.experimentData.delete({
   *   where: {
   *     // ... filter to delete one ExperimentData
   *   }
   * })
   * 
   */
  delete<T extends ExperimentDataDeleteArgs>(args: Prisma.SelectSubset<T, ExperimentDataDeleteArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ExperimentData.
   * @param {ExperimentDataUpdateArgs} args - Arguments to update one ExperimentData.
   * @example
   * // Update one ExperimentData
   * const experimentData = await prisma.experimentData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExperimentDataUpdateArgs>(args: Prisma.SelectSubset<T, ExperimentDataUpdateArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ExperimentData.
   * @param {ExperimentDataDeleteManyArgs} args - Arguments to filter ExperimentData to delete.
   * @example
   * // Delete a few ExperimentData
   * const { count } = await prisma.experimentData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExperimentDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExperimentDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExperimentData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExperimentData
   * const experimentData = await prisma.experimentData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExperimentDataUpdateManyArgs>(args: Prisma.SelectSubset<T, ExperimentDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExperimentData and returns the data updated in the database.
   * @param {ExperimentDataUpdateManyAndReturnArgs} args - Arguments to update many ExperimentData.
   * @example
   * // Update many ExperimentData
   * const experimentData = await prisma.experimentData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ExperimentData and only return the `id`
   * const experimentDataWithIdOnly = await prisma.experimentData.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExperimentDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExperimentDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ExperimentData.
   * @param {ExperimentDataUpsertArgs} args - Arguments to update or create a ExperimentData.
   * @example
   * // Update or create a ExperimentData
   * const experimentData = await prisma.experimentData.upsert({
   *   create: {
   *     // ... data to create a ExperimentData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExperimentData we want to update
   *   }
   * })
   */
  upsert<T extends ExperimentDataUpsertArgs>(args: Prisma.SelectSubset<T, ExperimentDataUpsertArgs<ExtArgs>>): Prisma.Prisma__ExperimentDataClient<runtime.Types.Result.GetResult<Prisma.$ExperimentDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ExperimentData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataCountArgs} args - Arguments to filter ExperimentData to count.
   * @example
   * // Count the number of ExperimentData
   * const count = await prisma.experimentData.count({
   *   where: {
   *     // ... the filter for the ExperimentData we want to count
   *   }
   * })
  **/
  count<T extends ExperimentDataCountArgs>(
    args?: Prisma.Subset<T, ExperimentDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExperimentDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExperimentData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExperimentDataAggregateArgs>(args: Prisma.Subset<T, ExperimentDataAggregateArgs>): Prisma.PrismaPromise<GetExperimentDataAggregateType<T>>

  /**
   * Group by ExperimentData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperimentDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExperimentDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExperimentDataGroupByArgs['orderBy'] }
      : { orderBy?: ExperimentDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExperimentDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExperimentDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ExperimentData model
 */
readonly fields: ExperimentDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExperimentData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExperimentDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  experiment<T extends Prisma.ExperimentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ExperimentDefaultArgs<ExtArgs>>): Prisma.Prisma__ExperimentClient<runtime.Types.Result.GetResult<Prisma.$ExperimentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ExperimentData model
 */
export interface ExperimentDataFieldRefs {
  readonly id: Prisma.FieldRef<"ExperimentData", 'String'>
  readonly experimentId: Prisma.FieldRef<"ExperimentData", 'String'>
  readonly fileType: Prisma.FieldRef<"ExperimentData", 'String'>
  readonly fileName: Prisma.FieldRef<"ExperimentData", 'String'>
  readonly fileUrl: Prisma.FieldRef<"ExperimentData", 'String'>
  readonly parsedData: Prisma.FieldRef<"ExperimentData", 'Json'>
  readonly analysis: Prisma.FieldRef<"ExperimentData", 'Json'>
  readonly createdAt: Prisma.FieldRef<"ExperimentData", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ExperimentData findUnique
 */
export type ExperimentDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * Filter, which ExperimentData to fetch.
   */
  where: Prisma.ExperimentDataWhereUniqueInput
}

/**
 * ExperimentData findUniqueOrThrow
 */
export type ExperimentDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * Filter, which ExperimentData to fetch.
   */
  where: Prisma.ExperimentDataWhereUniqueInput
}

/**
 * ExperimentData findFirst
 */
export type ExperimentDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * Filter, which ExperimentData to fetch.
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperimentData to fetch.
   */
  orderBy?: Prisma.ExperimentDataOrderByWithRelationInput | Prisma.ExperimentDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExperimentData.
   */
  cursor?: Prisma.ExperimentDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperimentData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperimentData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExperimentData.
   */
  distinct?: Prisma.ExperimentDataScalarFieldEnum | Prisma.ExperimentDataScalarFieldEnum[]
}

/**
 * ExperimentData findFirstOrThrow
 */
export type ExperimentDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * Filter, which ExperimentData to fetch.
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperimentData to fetch.
   */
  orderBy?: Prisma.ExperimentDataOrderByWithRelationInput | Prisma.ExperimentDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExperimentData.
   */
  cursor?: Prisma.ExperimentDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperimentData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperimentData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExperimentData.
   */
  distinct?: Prisma.ExperimentDataScalarFieldEnum | Prisma.ExperimentDataScalarFieldEnum[]
}

/**
 * ExperimentData findMany
 */
export type ExperimentDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * Filter, which ExperimentData to fetch.
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperimentData to fetch.
   */
  orderBy?: Prisma.ExperimentDataOrderByWithRelationInput | Prisma.ExperimentDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ExperimentData.
   */
  cursor?: Prisma.ExperimentDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperimentData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperimentData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExperimentData.
   */
  distinct?: Prisma.ExperimentDataScalarFieldEnum | Prisma.ExperimentDataScalarFieldEnum[]
}

/**
 * ExperimentData create
 */
export type ExperimentDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * The data needed to create a ExperimentData.
   */
  data: Prisma.XOR<Prisma.ExperimentDataCreateInput, Prisma.ExperimentDataUncheckedCreateInput>
}

/**
 * ExperimentData createMany
 */
export type ExperimentDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ExperimentData.
   */
  data: Prisma.ExperimentDataCreateManyInput | Prisma.ExperimentDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExperimentData createManyAndReturn
 */
export type ExperimentDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * The data used to create many ExperimentData.
   */
  data: Prisma.ExperimentDataCreateManyInput | Prisma.ExperimentDataCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ExperimentData update
 */
export type ExperimentDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * The data needed to update a ExperimentData.
   */
  data: Prisma.XOR<Prisma.ExperimentDataUpdateInput, Prisma.ExperimentDataUncheckedUpdateInput>
  /**
   * Choose, which ExperimentData to update.
   */
  where: Prisma.ExperimentDataWhereUniqueInput
}

/**
 * ExperimentData updateMany
 */
export type ExperimentDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ExperimentData.
   */
  data: Prisma.XOR<Prisma.ExperimentDataUpdateManyMutationInput, Prisma.ExperimentDataUncheckedUpdateManyInput>
  /**
   * Filter which ExperimentData to update
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * Limit how many ExperimentData to update.
   */
  limit?: number
}

/**
 * ExperimentData updateManyAndReturn
 */
export type ExperimentDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * The data used to update ExperimentData.
   */
  data: Prisma.XOR<Prisma.ExperimentDataUpdateManyMutationInput, Prisma.ExperimentDataUncheckedUpdateManyInput>
  /**
   * Filter which ExperimentData to update
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * Limit how many ExperimentData to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ExperimentData upsert
 */
export type ExperimentDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * The filter to search for the ExperimentData to update in case it exists.
   */
  where: Prisma.ExperimentDataWhereUniqueInput
  /**
   * In case the ExperimentData found by the `where` argument doesn't exist, create a new ExperimentData with this data.
   */
  create: Prisma.XOR<Prisma.ExperimentDataCreateInput, Prisma.ExperimentDataUncheckedCreateInput>
  /**
   * In case the ExperimentData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExperimentDataUpdateInput, Prisma.ExperimentDataUncheckedUpdateInput>
}

/**
 * ExperimentData delete
 */
export type ExperimentDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
  /**
   * Filter which ExperimentData to delete.
   */
  where: Prisma.ExperimentDataWhereUniqueInput
}

/**
 * ExperimentData deleteMany
 */
export type ExperimentDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExperimentData to delete
   */
  where?: Prisma.ExperimentDataWhereInput
  /**
   * Limit how many ExperimentData to delete.
   */
  limit?: number
}

/**
 * ExperimentData without action
 */
export type ExperimentDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperimentData
   */
  select?: Prisma.ExperimentDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperimentData
   */
  omit?: Prisma.ExperimentDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentDataInclude<ExtArgs> | null
}
