
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Extraction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Extraction
 * 
 */
export type ExtractionModel = runtime.Types.Result.DefaultSelection<Prisma.$ExtractionPayload>

export type AggregateExtraction = {
  _count: ExtractionCountAggregateOutputType | null
  _avg: ExtractionAvgAggregateOutputType | null
  _sum: ExtractionSumAggregateOutputType | null
  _min: ExtractionMinAggregateOutputType | null
  _max: ExtractionMaxAggregateOutputType | null
}

export type ExtractionAvgAggregateOutputType = {
  confidence: number | null
}

export type ExtractionSumAggregateOutputType = {
  confidence: number | null
}

export type ExtractionMinAggregateOutputType = {
  id: string | null
  paperId: string | null
  drugName: string | null
  drugConc: string | null
  cellLine: string | null
  pathway: string | null
  pathwayDir: string | null
  phenotype: string | null
  phenotypeDir: string | null
  method: string | null
  conclusion: string | null
  rawText: string | null
  confidence: number | null
  verified: boolean | null
  createdAt: Date | null
}

export type ExtractionMaxAggregateOutputType = {
  id: string | null
  paperId: string | null
  drugName: string | null
  drugConc: string | null
  cellLine: string | null
  pathway: string | null
  pathwayDir: string | null
  phenotype: string | null
  phenotypeDir: string | null
  method: string | null
  conclusion: string | null
  rawText: string | null
  confidence: number | null
  verified: boolean | null
  createdAt: Date | null
}

export type ExtractionCountAggregateOutputType = {
  id: number
  paperId: number
  drugName: number
  drugConc: number
  cellLine: number
  pathway: number
  pathwayDir: number
  phenotype: number
  phenotypeDir: number
  method: number
  conclusion: number
  rawText: number
  confidence: number
  verified: number
  createdAt: number
  _all: number
}


export type ExtractionAvgAggregateInputType = {
  confidence?: true
}

export type ExtractionSumAggregateInputType = {
  confidence?: true
}

export type ExtractionMinAggregateInputType = {
  id?: true
  paperId?: true
  drugName?: true
  drugConc?: true
  cellLine?: true
  pathway?: true
  pathwayDir?: true
  phenotype?: true
  phenotypeDir?: true
  method?: true
  conclusion?: true
  rawText?: true
  confidence?: true
  verified?: true
  createdAt?: true
}

export type ExtractionMaxAggregateInputType = {
  id?: true
  paperId?: true
  drugName?: true
  drugConc?: true
  cellLine?: true
  pathway?: true
  pathwayDir?: true
  phenotype?: true
  phenotypeDir?: true
  method?: true
  conclusion?: true
  rawText?: true
  confidence?: true
  verified?: true
  createdAt?: true
}

export type ExtractionCountAggregateInputType = {
  id?: true
  paperId?: true
  drugName?: true
  drugConc?: true
  cellLine?: true
  pathway?: true
  pathwayDir?: true
  phenotype?: true
  phenotypeDir?: true
  method?: true
  conclusion?: true
  rawText?: true
  confidence?: true
  verified?: true
  createdAt?: true
  _all?: true
}

export type ExtractionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Extraction to aggregate.
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Extractions to fetch.
   */
  orderBy?: Prisma.ExtractionOrderByWithRelationInput | Prisma.ExtractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExtractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Extractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Extractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Extractions
  **/
  _count?: true | ExtractionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExtractionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExtractionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExtractionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExtractionMaxAggregateInputType
}

export type GetExtractionAggregateType<T extends ExtractionAggregateArgs> = {
      [P in keyof T & keyof AggregateExtraction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExtraction[P]>
    : Prisma.GetScalarType<T[P], AggregateExtraction[P]>
}




export type ExtractionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExtractionWhereInput
  orderBy?: Prisma.ExtractionOrderByWithAggregationInput | Prisma.ExtractionOrderByWithAggregationInput[]
  by: Prisma.ExtractionScalarFieldEnum[] | Prisma.ExtractionScalarFieldEnum
  having?: Prisma.ExtractionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExtractionCountAggregateInputType | true
  _avg?: ExtractionAvgAggregateInputType
  _sum?: ExtractionSumAggregateInputType
  _min?: ExtractionMinAggregateInputType
  _max?: ExtractionMaxAggregateInputType
}

export type ExtractionGroupByOutputType = {
  id: string
  paperId: string
  drugName: string | null
  drugConc: string | null
  cellLine: string | null
  pathway: string | null
  pathwayDir: string | null
  phenotype: string | null
  phenotypeDir: string | null
  method: string | null
  conclusion: string | null
  rawText: string | null
  confidence: number | null
  verified: boolean
  createdAt: Date
  _count: ExtractionCountAggregateOutputType | null
  _avg: ExtractionAvgAggregateOutputType | null
  _sum: ExtractionSumAggregateOutputType | null
  _min: ExtractionMinAggregateOutputType | null
  _max: ExtractionMaxAggregateOutputType | null
}

export type GetExtractionGroupByPayload<T extends ExtractionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExtractionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExtractionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExtractionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExtractionGroupByOutputType[P]>
      }
    >
  >



export type ExtractionWhereInput = {
  AND?: Prisma.ExtractionWhereInput | Prisma.ExtractionWhereInput[]
  OR?: Prisma.ExtractionWhereInput[]
  NOT?: Prisma.ExtractionWhereInput | Prisma.ExtractionWhereInput[]
  id?: Prisma.StringFilter<"Extraction"> | string
  paperId?: Prisma.StringFilter<"Extraction"> | string
  drugName?: Prisma.StringNullableFilter<"Extraction"> | string | null
  drugConc?: Prisma.StringNullableFilter<"Extraction"> | string | null
  cellLine?: Prisma.StringNullableFilter<"Extraction"> | string | null
  pathway?: Prisma.StringNullableFilter<"Extraction"> | string | null
  pathwayDir?: Prisma.StringNullableFilter<"Extraction"> | string | null
  phenotype?: Prisma.StringNullableFilter<"Extraction"> | string | null
  phenotypeDir?: Prisma.StringNullableFilter<"Extraction"> | string | null
  method?: Prisma.StringNullableFilter<"Extraction"> | string | null
  conclusion?: Prisma.StringNullableFilter<"Extraction"> | string | null
  rawText?: Prisma.StringNullableFilter<"Extraction"> | string | null
  confidence?: Prisma.FloatNullableFilter<"Extraction"> | number | null
  verified?: Prisma.BoolFilter<"Extraction"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Extraction"> | Date | string
  paper?: Prisma.XOR<Prisma.PaperScalarRelationFilter, Prisma.PaperWhereInput>
}

export type ExtractionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  paperId?: Prisma.SortOrder
  drugName?: Prisma.SortOrderInput | Prisma.SortOrder
  drugConc?: Prisma.SortOrderInput | Prisma.SortOrder
  cellLine?: Prisma.SortOrderInput | Prisma.SortOrder
  pathway?: Prisma.SortOrderInput | Prisma.SortOrder
  pathwayDir?: Prisma.SortOrderInput | Prisma.SortOrder
  phenotype?: Prisma.SortOrderInput | Prisma.SortOrder
  phenotypeDir?: Prisma.SortOrderInput | Prisma.SortOrder
  method?: Prisma.SortOrderInput | Prisma.SortOrder
  conclusion?: Prisma.SortOrderInput | Prisma.SortOrder
  rawText?: Prisma.SortOrderInput | Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  verified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  paper?: Prisma.PaperOrderByWithRelationInput
}

export type ExtractionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ExtractionWhereInput | Prisma.ExtractionWhereInput[]
  OR?: Prisma.ExtractionWhereInput[]
  NOT?: Prisma.ExtractionWhereInput | Prisma.ExtractionWhereInput[]
  paperId?: Prisma.StringFilter<"Extraction"> | string
  drugName?: Prisma.StringNullableFilter<"Extraction"> | string | null
  drugConc?: Prisma.StringNullableFilter<"Extraction"> | string | null
  cellLine?: Prisma.StringNullableFilter<"Extraction"> | string | null
  pathway?: Prisma.StringNullableFilter<"Extraction"> | string | null
  pathwayDir?: Prisma.StringNullableFilter<"Extraction"> | string | null
  phenotype?: Prisma.StringNullableFilter<"Extraction"> | string | null
  phenotypeDir?: Prisma.StringNullableFilter<"Extraction"> | string | null
  method?: Prisma.StringNullableFilter<"Extraction"> | string | null
  conclusion?: Prisma.StringNullableFilter<"Extraction"> | string | null
  rawText?: Prisma.StringNullableFilter<"Extraction"> | string | null
  confidence?: Prisma.FloatNullableFilter<"Extraction"> | number | null
  verified?: Prisma.BoolFilter<"Extraction"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Extraction"> | Date | string
  paper?: Prisma.XOR<Prisma.PaperScalarRelationFilter, Prisma.PaperWhereInput>
}, "id">

export type ExtractionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  paperId?: Prisma.SortOrder
  drugName?: Prisma.SortOrderInput | Prisma.SortOrder
  drugConc?: Prisma.SortOrderInput | Prisma.SortOrder
  cellLine?: Prisma.SortOrderInput | Prisma.SortOrder
  pathway?: Prisma.SortOrderInput | Prisma.SortOrder
  pathwayDir?: Prisma.SortOrderInput | Prisma.SortOrder
  phenotype?: Prisma.SortOrderInput | Prisma.SortOrder
  phenotypeDir?: Prisma.SortOrderInput | Prisma.SortOrder
  method?: Prisma.SortOrderInput | Prisma.SortOrder
  conclusion?: Prisma.SortOrderInput | Prisma.SortOrder
  rawText?: Prisma.SortOrderInput | Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  verified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ExtractionCountOrderByAggregateInput
  _avg?: Prisma.ExtractionAvgOrderByAggregateInput
  _max?: Prisma.ExtractionMaxOrderByAggregateInput
  _min?: Prisma.ExtractionMinOrderByAggregateInput
  _sum?: Prisma.ExtractionSumOrderByAggregateInput
}

export type ExtractionScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExtractionScalarWhereWithAggregatesInput | Prisma.ExtractionScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExtractionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExtractionScalarWhereWithAggregatesInput | Prisma.ExtractionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Extraction"> | string
  paperId?: Prisma.StringWithAggregatesFilter<"Extraction"> | string
  drugName?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  drugConc?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  cellLine?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  pathway?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  pathwayDir?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  phenotype?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  phenotypeDir?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  method?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  conclusion?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  rawText?: Prisma.StringNullableWithAggregatesFilter<"Extraction"> | string | null
  confidence?: Prisma.FloatNullableWithAggregatesFilter<"Extraction"> | number | null
  verified?: Prisma.BoolWithAggregatesFilter<"Extraction"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Extraction"> | Date | string
}

export type ExtractionCreateInput = {
  id?: string
  drugName?: string | null
  drugConc?: string | null
  cellLine?: string | null
  pathway?: string | null
  pathwayDir?: string | null
  phenotype?: string | null
  phenotypeDir?: string | null
  method?: string | null
  conclusion?: string | null
  rawText?: string | null
  confidence?: number | null
  verified?: boolean
  createdAt?: Date | string
  paper: Prisma.PaperCreateNestedOneWithoutExtractionsInput
}

export type ExtractionUncheckedCreateInput = {
  id?: string
  paperId: string
  drugName?: string | null
  drugConc?: string | null
  cellLine?: string | null
  pathway?: string | null
  pathwayDir?: string | null
  phenotype?: string | null
  phenotypeDir?: string | null
  method?: string | null
  conclusion?: string | null
  rawText?: string | null
  confidence?: number | null
  verified?: boolean
  createdAt?: Date | string
}

export type ExtractionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paper?: Prisma.PaperUpdateOneRequiredWithoutExtractionsNestedInput
}

export type ExtractionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  paperId?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractionCreateManyInput = {
  id?: string
  paperId: string
  drugName?: string | null
  drugConc?: string | null
  cellLine?: string | null
  pathway?: string | null
  pathwayDir?: string | null
  phenotype?: string | null
  phenotypeDir?: string | null
  method?: string | null
  conclusion?: string | null
  rawText?: string | null
  confidence?: number | null
  verified?: boolean
  createdAt?: Date | string
}

export type ExtractionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  paperId?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractionListRelationFilter = {
  every?: Prisma.ExtractionWhereInput
  some?: Prisma.ExtractionWhereInput
  none?: Prisma.ExtractionWhereInput
}

export type ExtractionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExtractionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paperId?: Prisma.SortOrder
  drugName?: Prisma.SortOrder
  drugConc?: Prisma.SortOrder
  cellLine?: Prisma.SortOrder
  pathway?: Prisma.SortOrder
  pathwayDir?: Prisma.SortOrder
  phenotype?: Prisma.SortOrder
  phenotypeDir?: Prisma.SortOrder
  method?: Prisma.SortOrder
  conclusion?: Prisma.SortOrder
  rawText?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExtractionAvgOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type ExtractionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paperId?: Prisma.SortOrder
  drugName?: Prisma.SortOrder
  drugConc?: Prisma.SortOrder
  cellLine?: Prisma.SortOrder
  pathway?: Prisma.SortOrder
  pathwayDir?: Prisma.SortOrder
  phenotype?: Prisma.SortOrder
  phenotypeDir?: Prisma.SortOrder
  method?: Prisma.SortOrder
  conclusion?: Prisma.SortOrder
  rawText?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExtractionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paperId?: Prisma.SortOrder
  drugName?: Prisma.SortOrder
  drugConc?: Prisma.SortOrder
  cellLine?: Prisma.SortOrder
  pathway?: Prisma.SortOrder
  pathwayDir?: Prisma.SortOrder
  phenotype?: Prisma.SortOrder
  phenotypeDir?: Prisma.SortOrder
  method?: Prisma.SortOrder
  conclusion?: Prisma.SortOrder
  rawText?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ExtractionSumOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type ExtractionCreateNestedManyWithoutPaperInput = {
  create?: Prisma.XOR<Prisma.ExtractionCreateWithoutPaperInput, Prisma.ExtractionUncheckedCreateWithoutPaperInput> | Prisma.ExtractionCreateWithoutPaperInput[] | Prisma.ExtractionUncheckedCreateWithoutPaperInput[]
  connectOrCreate?: Prisma.ExtractionCreateOrConnectWithoutPaperInput | Prisma.ExtractionCreateOrConnectWithoutPaperInput[]
  createMany?: Prisma.ExtractionCreateManyPaperInputEnvelope
  connect?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
}

export type ExtractionUncheckedCreateNestedManyWithoutPaperInput = {
  create?: Prisma.XOR<Prisma.ExtractionCreateWithoutPaperInput, Prisma.ExtractionUncheckedCreateWithoutPaperInput> | Prisma.ExtractionCreateWithoutPaperInput[] | Prisma.ExtractionUncheckedCreateWithoutPaperInput[]
  connectOrCreate?: Prisma.ExtractionCreateOrConnectWithoutPaperInput | Prisma.ExtractionCreateOrConnectWithoutPaperInput[]
  createMany?: Prisma.ExtractionCreateManyPaperInputEnvelope
  connect?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
}

export type ExtractionUpdateManyWithoutPaperNestedInput = {
  create?: Prisma.XOR<Prisma.ExtractionCreateWithoutPaperInput, Prisma.ExtractionUncheckedCreateWithoutPaperInput> | Prisma.ExtractionCreateWithoutPaperInput[] | Prisma.ExtractionUncheckedCreateWithoutPaperInput[]
  connectOrCreate?: Prisma.ExtractionCreateOrConnectWithoutPaperInput | Prisma.ExtractionCreateOrConnectWithoutPaperInput[]
  upsert?: Prisma.ExtractionUpsertWithWhereUniqueWithoutPaperInput | Prisma.ExtractionUpsertWithWhereUniqueWithoutPaperInput[]
  createMany?: Prisma.ExtractionCreateManyPaperInputEnvelope
  set?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  disconnect?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  delete?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  connect?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  update?: Prisma.ExtractionUpdateWithWhereUniqueWithoutPaperInput | Prisma.ExtractionUpdateWithWhereUniqueWithoutPaperInput[]
  updateMany?: Prisma.ExtractionUpdateManyWithWhereWithoutPaperInput | Prisma.ExtractionUpdateManyWithWhereWithoutPaperInput[]
  deleteMany?: Prisma.ExtractionScalarWhereInput | Prisma.ExtractionScalarWhereInput[]
}

export type ExtractionUncheckedUpdateManyWithoutPaperNestedInput = {
  create?: Prisma.XOR<Prisma.ExtractionCreateWithoutPaperInput, Prisma.ExtractionUncheckedCreateWithoutPaperInput> | Prisma.ExtractionCreateWithoutPaperInput[] | Prisma.ExtractionUncheckedCreateWithoutPaperInput[]
  connectOrCreate?: Prisma.ExtractionCreateOrConnectWithoutPaperInput | Prisma.ExtractionCreateOrConnectWithoutPaperInput[]
  upsert?: Prisma.ExtractionUpsertWithWhereUniqueWithoutPaperInput | Prisma.ExtractionUpsertWithWhereUniqueWithoutPaperInput[]
  createMany?: Prisma.ExtractionCreateManyPaperInputEnvelope
  set?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  disconnect?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  delete?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  connect?: Prisma.ExtractionWhereUniqueInput | Prisma.ExtractionWhereUniqueInput[]
  update?: Prisma.ExtractionUpdateWithWhereUniqueWithoutPaperInput | Prisma.ExtractionUpdateWithWhereUniqueWithoutPaperInput[]
  updateMany?: Prisma.ExtractionUpdateManyWithWhereWithoutPaperInput | Prisma.ExtractionUpdateManyWithWhereWithoutPaperInput[]
  deleteMany?: Prisma.ExtractionScalarWhereInput | Prisma.ExtractionScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ExtractionCreateWithoutPaperInput = {
  id?: string
  drugName?: string | null
  drugConc?: string | null
  cellLine?: string | null
  pathway?: string | null
  pathwayDir?: string | null
  phenotype?: string | null
  phenotypeDir?: string | null
  method?: string | null
  conclusion?: string | null
  rawText?: string | null
  confidence?: number | null
  verified?: boolean
  createdAt?: Date | string
}

export type ExtractionUncheckedCreateWithoutPaperInput = {
  id?: string
  drugName?: string | null
  drugConc?: string | null
  cellLine?: string | null
  pathway?: string | null
  pathwayDir?: string | null
  phenotype?: string | null
  phenotypeDir?: string | null
  method?: string | null
  conclusion?: string | null
  rawText?: string | null
  confidence?: number | null
  verified?: boolean
  createdAt?: Date | string
}

export type ExtractionCreateOrConnectWithoutPaperInput = {
  where: Prisma.ExtractionWhereUniqueInput
  create: Prisma.XOR<Prisma.ExtractionCreateWithoutPaperInput, Prisma.ExtractionUncheckedCreateWithoutPaperInput>
}

export type ExtractionCreateManyPaperInputEnvelope = {
  data: Prisma.ExtractionCreateManyPaperInput | Prisma.ExtractionCreateManyPaperInput[]
  skipDuplicates?: boolean
}

export type ExtractionUpsertWithWhereUniqueWithoutPaperInput = {
  where: Prisma.ExtractionWhereUniqueInput
  update: Prisma.XOR<Prisma.ExtractionUpdateWithoutPaperInput, Prisma.ExtractionUncheckedUpdateWithoutPaperInput>
  create: Prisma.XOR<Prisma.ExtractionCreateWithoutPaperInput, Prisma.ExtractionUncheckedCreateWithoutPaperInput>
}

export type ExtractionUpdateWithWhereUniqueWithoutPaperInput = {
  where: Prisma.ExtractionWhereUniqueInput
  data: Prisma.XOR<Prisma.ExtractionUpdateWithoutPaperInput, Prisma.ExtractionUncheckedUpdateWithoutPaperInput>
}

export type ExtractionUpdateManyWithWhereWithoutPaperInput = {
  where: Prisma.ExtractionScalarWhereInput
  data: Prisma.XOR<Prisma.ExtractionUpdateManyMutationInput, Prisma.ExtractionUncheckedUpdateManyWithoutPaperInput>
}

export type ExtractionScalarWhereInput = {
  AND?: Prisma.ExtractionScalarWhereInput | Prisma.ExtractionScalarWhereInput[]
  OR?: Prisma.ExtractionScalarWhereInput[]
  NOT?: Prisma.ExtractionScalarWhereInput | Prisma.ExtractionScalarWhereInput[]
  id?: Prisma.StringFilter<"Extraction"> | string
  paperId?: Prisma.StringFilter<"Extraction"> | string
  drugName?: Prisma.StringNullableFilter<"Extraction"> | string | null
  drugConc?: Prisma.StringNullableFilter<"Extraction"> | string | null
  cellLine?: Prisma.StringNullableFilter<"Extraction"> | string | null
  pathway?: Prisma.StringNullableFilter<"Extraction"> | string | null
  pathwayDir?: Prisma.StringNullableFilter<"Extraction"> | string | null
  phenotype?: Prisma.StringNullableFilter<"Extraction"> | string | null
  phenotypeDir?: Prisma.StringNullableFilter<"Extraction"> | string | null
  method?: Prisma.StringNullableFilter<"Extraction"> | string | null
  conclusion?: Prisma.StringNullableFilter<"Extraction"> | string | null
  rawText?: Prisma.StringNullableFilter<"Extraction"> | string | null
  confidence?: Prisma.FloatNullableFilter<"Extraction"> | number | null
  verified?: Prisma.BoolFilter<"Extraction"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Extraction"> | Date | string
}

export type ExtractionCreateManyPaperInput = {
  id?: string
  drugName?: string | null
  drugConc?: string | null
  cellLine?: string | null
  pathway?: string | null
  pathwayDir?: string | null
  phenotype?: string | null
  phenotypeDir?: string | null
  method?: string | null
  conclusion?: string | null
  rawText?: string | null
  confidence?: number | null
  verified?: boolean
  createdAt?: Date | string
}

export type ExtractionUpdateWithoutPaperInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractionUncheckedUpdateWithoutPaperInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExtractionUncheckedUpdateManyWithoutPaperInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  drugName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  drugConc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cellLine?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathway?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pathwayDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phenotypeDir?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conclusion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ExtractionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paperId?: boolean
  drugName?: boolean
  drugConc?: boolean
  cellLine?: boolean
  pathway?: boolean
  pathwayDir?: boolean
  phenotype?: boolean
  phenotypeDir?: boolean
  method?: boolean
  conclusion?: boolean
  rawText?: boolean
  confidence?: boolean
  verified?: boolean
  createdAt?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["extraction"]>

export type ExtractionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paperId?: boolean
  drugName?: boolean
  drugConc?: boolean
  cellLine?: boolean
  pathway?: boolean
  pathwayDir?: boolean
  phenotype?: boolean
  phenotypeDir?: boolean
  method?: boolean
  conclusion?: boolean
  rawText?: boolean
  confidence?: boolean
  verified?: boolean
  createdAt?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["extraction"]>

export type ExtractionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paperId?: boolean
  drugName?: boolean
  drugConc?: boolean
  cellLine?: boolean
  pathway?: boolean
  pathwayDir?: boolean
  phenotype?: boolean
  phenotypeDir?: boolean
  method?: boolean
  conclusion?: boolean
  rawText?: boolean
  confidence?: boolean
  verified?: boolean
  createdAt?: boolean
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}, ExtArgs["result"]["extraction"]>

export type ExtractionSelectScalar = {
  id?: boolean
  paperId?: boolean
  drugName?: boolean
  drugConc?: boolean
  cellLine?: boolean
  pathway?: boolean
  pathwayDir?: boolean
  phenotype?: boolean
  phenotypeDir?: boolean
  method?: boolean
  conclusion?: boolean
  rawText?: boolean
  confidence?: boolean
  verified?: boolean
  createdAt?: boolean
}

export type ExtractionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "paperId" | "drugName" | "drugConc" | "cellLine" | "pathway" | "pathwayDir" | "phenotype" | "phenotypeDir" | "method" | "conclusion" | "rawText" | "confidence" | "verified" | "createdAt", ExtArgs["result"]["extraction"]>
export type ExtractionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}
export type ExtractionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}
export type ExtractionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  paper?: boolean | Prisma.PaperDefaultArgs<ExtArgs>
}

export type $ExtractionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Extraction"
  objects: {
    paper: Prisma.$PaperPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    paperId: string
    drugName: string | null
    drugConc: string | null
    cellLine: string | null
    pathway: string | null
    pathwayDir: string | null
    phenotype: string | null
    phenotypeDir: string | null
    method: string | null
    conclusion: string | null
    rawText: string | null
    confidence: number | null
    verified: boolean
    createdAt: Date
  }, ExtArgs["result"]["extraction"]>
  composites: {}
}

export type ExtractionGetPayload<S extends boolean | null | undefined | ExtractionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExtractionPayload, S>

export type ExtractionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExtractionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExtractionCountAggregateInputType | true
  }

export interface ExtractionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Extraction'], meta: { name: 'Extraction' } }
  /**
   * Find zero or one Extraction that matches the filter.
   * @param {ExtractionFindUniqueArgs} args - Arguments to find a Extraction
   * @example
   * // Get one Extraction
   * const extraction = await prisma.extraction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExtractionFindUniqueArgs>(args: Prisma.SelectSubset<T, ExtractionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Extraction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExtractionFindUniqueOrThrowArgs} args - Arguments to find a Extraction
   * @example
   * // Get one Extraction
   * const extraction = await prisma.extraction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExtractionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExtractionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Extraction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionFindFirstArgs} args - Arguments to find a Extraction
   * @example
   * // Get one Extraction
   * const extraction = await prisma.extraction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExtractionFindFirstArgs>(args?: Prisma.SelectSubset<T, ExtractionFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Extraction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionFindFirstOrThrowArgs} args - Arguments to find a Extraction
   * @example
   * // Get one Extraction
   * const extraction = await prisma.extraction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExtractionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExtractionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Extractions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Extractions
   * const extractions = await prisma.extraction.findMany()
   * 
   * // Get first 10 Extractions
   * const extractions = await prisma.extraction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const extractionWithIdOnly = await prisma.extraction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExtractionFindManyArgs>(args?: Prisma.SelectSubset<T, ExtractionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Extraction.
   * @param {ExtractionCreateArgs} args - Arguments to create a Extraction.
   * @example
   * // Create one Extraction
   * const Extraction = await prisma.extraction.create({
   *   data: {
   *     // ... data to create a Extraction
   *   }
   * })
   * 
   */
  create<T extends ExtractionCreateArgs>(args: Prisma.SelectSubset<T, ExtractionCreateArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Extractions.
   * @param {ExtractionCreateManyArgs} args - Arguments to create many Extractions.
   * @example
   * // Create many Extractions
   * const extraction = await prisma.extraction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExtractionCreateManyArgs>(args?: Prisma.SelectSubset<T, ExtractionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Extractions and returns the data saved in the database.
   * @param {ExtractionCreateManyAndReturnArgs} args - Arguments to create many Extractions.
   * @example
   * // Create many Extractions
   * const extraction = await prisma.extraction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Extractions and only return the `id`
   * const extractionWithIdOnly = await prisma.extraction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExtractionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExtractionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Extraction.
   * @param {ExtractionDeleteArgs} args - Arguments to delete one Extraction.
   * @example
   * // Delete one Extraction
   * const Extraction = await prisma.extraction.delete({
   *   where: {
   *     // ... filter to delete one Extraction
   *   }
   * })
   * 
   */
  delete<T extends ExtractionDeleteArgs>(args: Prisma.SelectSubset<T, ExtractionDeleteArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Extraction.
   * @param {ExtractionUpdateArgs} args - Arguments to update one Extraction.
   * @example
   * // Update one Extraction
   * const extraction = await prisma.extraction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExtractionUpdateArgs>(args: Prisma.SelectSubset<T, ExtractionUpdateArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Extractions.
   * @param {ExtractionDeleteManyArgs} args - Arguments to filter Extractions to delete.
   * @example
   * // Delete a few Extractions
   * const { count } = await prisma.extraction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExtractionDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExtractionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Extractions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Extractions
   * const extraction = await prisma.extraction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExtractionUpdateManyArgs>(args: Prisma.SelectSubset<T, ExtractionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Extractions and returns the data updated in the database.
   * @param {ExtractionUpdateManyAndReturnArgs} args - Arguments to update many Extractions.
   * @example
   * // Update many Extractions
   * const extraction = await prisma.extraction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Extractions and only return the `id`
   * const extractionWithIdOnly = await prisma.extraction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExtractionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExtractionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Extraction.
   * @param {ExtractionUpsertArgs} args - Arguments to update or create a Extraction.
   * @example
   * // Update or create a Extraction
   * const extraction = await prisma.extraction.upsert({
   *   create: {
   *     // ... data to create a Extraction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Extraction we want to update
   *   }
   * })
   */
  upsert<T extends ExtractionUpsertArgs>(args: Prisma.SelectSubset<T, ExtractionUpsertArgs<ExtArgs>>): Prisma.Prisma__ExtractionClient<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Extractions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionCountArgs} args - Arguments to filter Extractions to count.
   * @example
   * // Count the number of Extractions
   * const count = await prisma.extraction.count({
   *   where: {
   *     // ... the filter for the Extractions we want to count
   *   }
   * })
  **/
  count<T extends ExtractionCountArgs>(
    args?: Prisma.Subset<T, ExtractionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExtractionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Extraction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExtractionAggregateArgs>(args: Prisma.Subset<T, ExtractionAggregateArgs>): Prisma.PrismaPromise<GetExtractionAggregateType<T>>

  /**
   * Group by Extraction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExtractionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExtractionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExtractionGroupByArgs['orderBy'] }
      : { orderBy?: ExtractionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExtractionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExtractionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Extraction model
 */
readonly fields: ExtractionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Extraction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExtractionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  paper<T extends Prisma.PaperDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PaperDefaultArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Extraction model
 */
export interface ExtractionFieldRefs {
  readonly id: Prisma.FieldRef<"Extraction", 'String'>
  readonly paperId: Prisma.FieldRef<"Extraction", 'String'>
  readonly drugName: Prisma.FieldRef<"Extraction", 'String'>
  readonly drugConc: Prisma.FieldRef<"Extraction", 'String'>
  readonly cellLine: Prisma.FieldRef<"Extraction", 'String'>
  readonly pathway: Prisma.FieldRef<"Extraction", 'String'>
  readonly pathwayDir: Prisma.FieldRef<"Extraction", 'String'>
  readonly phenotype: Prisma.FieldRef<"Extraction", 'String'>
  readonly phenotypeDir: Prisma.FieldRef<"Extraction", 'String'>
  readonly method: Prisma.FieldRef<"Extraction", 'String'>
  readonly conclusion: Prisma.FieldRef<"Extraction", 'String'>
  readonly rawText: Prisma.FieldRef<"Extraction", 'String'>
  readonly confidence: Prisma.FieldRef<"Extraction", 'Float'>
  readonly verified: Prisma.FieldRef<"Extraction", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Extraction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Extraction findUnique
 */
export type ExtractionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * Filter, which Extraction to fetch.
   */
  where: Prisma.ExtractionWhereUniqueInput
}

/**
 * Extraction findUniqueOrThrow
 */
export type ExtractionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * Filter, which Extraction to fetch.
   */
  where: Prisma.ExtractionWhereUniqueInput
}

/**
 * Extraction findFirst
 */
export type ExtractionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * Filter, which Extraction to fetch.
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Extractions to fetch.
   */
  orderBy?: Prisma.ExtractionOrderByWithRelationInput | Prisma.ExtractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Extractions.
   */
  cursor?: Prisma.ExtractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Extractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Extractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Extractions.
   */
  distinct?: Prisma.ExtractionScalarFieldEnum | Prisma.ExtractionScalarFieldEnum[]
}

/**
 * Extraction findFirstOrThrow
 */
export type ExtractionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * Filter, which Extraction to fetch.
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Extractions to fetch.
   */
  orderBy?: Prisma.ExtractionOrderByWithRelationInput | Prisma.ExtractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Extractions.
   */
  cursor?: Prisma.ExtractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Extractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Extractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Extractions.
   */
  distinct?: Prisma.ExtractionScalarFieldEnum | Prisma.ExtractionScalarFieldEnum[]
}

/**
 * Extraction findMany
 */
export type ExtractionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * Filter, which Extractions to fetch.
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Extractions to fetch.
   */
  orderBy?: Prisma.ExtractionOrderByWithRelationInput | Prisma.ExtractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Extractions.
   */
  cursor?: Prisma.ExtractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Extractions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Extractions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Extractions.
   */
  distinct?: Prisma.ExtractionScalarFieldEnum | Prisma.ExtractionScalarFieldEnum[]
}

/**
 * Extraction create
 */
export type ExtractionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * The data needed to create a Extraction.
   */
  data: Prisma.XOR<Prisma.ExtractionCreateInput, Prisma.ExtractionUncheckedCreateInput>
}

/**
 * Extraction createMany
 */
export type ExtractionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Extractions.
   */
  data: Prisma.ExtractionCreateManyInput | Prisma.ExtractionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Extraction createManyAndReturn
 */
export type ExtractionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * The data used to create many Extractions.
   */
  data: Prisma.ExtractionCreateManyInput | Prisma.ExtractionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Extraction update
 */
export type ExtractionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * The data needed to update a Extraction.
   */
  data: Prisma.XOR<Prisma.ExtractionUpdateInput, Prisma.ExtractionUncheckedUpdateInput>
  /**
   * Choose, which Extraction to update.
   */
  where: Prisma.ExtractionWhereUniqueInput
}

/**
 * Extraction updateMany
 */
export type ExtractionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Extractions.
   */
  data: Prisma.XOR<Prisma.ExtractionUpdateManyMutationInput, Prisma.ExtractionUncheckedUpdateManyInput>
  /**
   * Filter which Extractions to update
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * Limit how many Extractions to update.
   */
  limit?: number
}

/**
 * Extraction updateManyAndReturn
 */
export type ExtractionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * The data used to update Extractions.
   */
  data: Prisma.XOR<Prisma.ExtractionUpdateManyMutationInput, Prisma.ExtractionUncheckedUpdateManyInput>
  /**
   * Filter which Extractions to update
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * Limit how many Extractions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Extraction upsert
 */
export type ExtractionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * The filter to search for the Extraction to update in case it exists.
   */
  where: Prisma.ExtractionWhereUniqueInput
  /**
   * In case the Extraction found by the `where` argument doesn't exist, create a new Extraction with this data.
   */
  create: Prisma.XOR<Prisma.ExtractionCreateInput, Prisma.ExtractionUncheckedCreateInput>
  /**
   * In case the Extraction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExtractionUpdateInput, Prisma.ExtractionUncheckedUpdateInput>
}

/**
 * Extraction delete
 */
export type ExtractionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  /**
   * Filter which Extraction to delete.
   */
  where: Prisma.ExtractionWhereUniqueInput
}

/**
 * Extraction deleteMany
 */
export type ExtractionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Extractions to delete
   */
  where?: Prisma.ExtractionWhereInput
  /**
   * Limit how many Extractions to delete.
   */
  limit?: number
}

/**
 * Extraction without action
 */
export type ExtractionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
}
