
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Hypothesis` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Hypothesis
 * 
 */
export type HypothesisModel = runtime.Types.Result.DefaultSelection<Prisma.$HypothesisPayload>

export type AggregateHypothesis = {
  _count: HypothesisCountAggregateOutputType | null
  _min: HypothesisMinAggregateOutputType | null
  _max: HypothesisMaxAggregateOutputType | null
}

export type HypothesisMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  statement: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HypothesisMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  statement: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HypothesisCountAggregateOutputType = {
  id: number
  projectId: number
  statement: number
  status: number
  evidence: number
  basedOn: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type HypothesisMinAggregateInputType = {
  id?: true
  projectId?: true
  statement?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type HypothesisMaxAggregateInputType = {
  id?: true
  projectId?: true
  statement?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type HypothesisCountAggregateInputType = {
  id?: true
  projectId?: true
  statement?: true
  status?: true
  evidence?: true
  basedOn?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type HypothesisAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hypothesis to aggregate.
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hypotheses to fetch.
   */
  orderBy?: Prisma.HypothesisOrderByWithRelationInput | Prisma.HypothesisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HypothesisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hypotheses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hypotheses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Hypotheses
  **/
  _count?: true | HypothesisCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HypothesisMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HypothesisMaxAggregateInputType
}

export type GetHypothesisAggregateType<T extends HypothesisAggregateArgs> = {
      [P in keyof T & keyof AggregateHypothesis]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHypothesis[P]>
    : Prisma.GetScalarType<T[P], AggregateHypothesis[P]>
}




export type HypothesisGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HypothesisWhereInput
  orderBy?: Prisma.HypothesisOrderByWithAggregationInput | Prisma.HypothesisOrderByWithAggregationInput[]
  by: Prisma.HypothesisScalarFieldEnum[] | Prisma.HypothesisScalarFieldEnum
  having?: Prisma.HypothesisScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HypothesisCountAggregateInputType | true
  _min?: HypothesisMinAggregateInputType
  _max?: HypothesisMaxAggregateInputType
}

export type HypothesisGroupByOutputType = {
  id: string
  projectId: string
  statement: string
  status: string
  evidence: runtime.JsonValue | null
  basedOn: string[]
  createdAt: Date
  updatedAt: Date
  _count: HypothesisCountAggregateOutputType | null
  _min: HypothesisMinAggregateOutputType | null
  _max: HypothesisMaxAggregateOutputType | null
}

export type GetHypothesisGroupByPayload<T extends HypothesisGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HypothesisGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HypothesisGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HypothesisGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HypothesisGroupByOutputType[P]>
      }
    >
  >



export type HypothesisWhereInput = {
  AND?: Prisma.HypothesisWhereInput | Prisma.HypothesisWhereInput[]
  OR?: Prisma.HypothesisWhereInput[]
  NOT?: Prisma.HypothesisWhereInput | Prisma.HypothesisWhereInput[]
  id?: Prisma.StringFilter<"Hypothesis"> | string
  projectId?: Prisma.StringFilter<"Hypothesis"> | string
  statement?: Prisma.StringFilter<"Hypothesis"> | string
  status?: Prisma.StringFilter<"Hypothesis"> | string
  evidence?: Prisma.JsonNullableFilter<"Hypothesis">
  basedOn?: Prisma.StringNullableListFilter<"Hypothesis">
  createdAt?: Prisma.DateTimeFilter<"Hypothesis"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hypothesis"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  experiments?: Prisma.ExperimentListRelationFilter
}

export type HypothesisOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  statement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  evidence?: Prisma.SortOrderInput | Prisma.SortOrder
  basedOn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  experiments?: Prisma.ExperimentOrderByRelationAggregateInput
}

export type HypothesisWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.HypothesisWhereInput | Prisma.HypothesisWhereInput[]
  OR?: Prisma.HypothesisWhereInput[]
  NOT?: Prisma.HypothesisWhereInput | Prisma.HypothesisWhereInput[]
  projectId?: Prisma.StringFilter<"Hypothesis"> | string
  statement?: Prisma.StringFilter<"Hypothesis"> | string
  status?: Prisma.StringFilter<"Hypothesis"> | string
  evidence?: Prisma.JsonNullableFilter<"Hypothesis">
  basedOn?: Prisma.StringNullableListFilter<"Hypothesis">
  createdAt?: Prisma.DateTimeFilter<"Hypothesis"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hypothesis"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  experiments?: Prisma.ExperimentListRelationFilter
}, "id">

export type HypothesisOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  statement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  evidence?: Prisma.SortOrderInput | Prisma.SortOrder
  basedOn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.HypothesisCountOrderByAggregateInput
  _max?: Prisma.HypothesisMaxOrderByAggregateInput
  _min?: Prisma.HypothesisMinOrderByAggregateInput
}

export type HypothesisScalarWhereWithAggregatesInput = {
  AND?: Prisma.HypothesisScalarWhereWithAggregatesInput | Prisma.HypothesisScalarWhereWithAggregatesInput[]
  OR?: Prisma.HypothesisScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HypothesisScalarWhereWithAggregatesInput | Prisma.HypothesisScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Hypothesis"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Hypothesis"> | string
  statement?: Prisma.StringWithAggregatesFilter<"Hypothesis"> | string
  status?: Prisma.StringWithAggregatesFilter<"Hypothesis"> | string
  evidence?: Prisma.JsonNullableWithAggregatesFilter<"Hypothesis">
  basedOn?: Prisma.StringNullableListFilter<"Hypothesis">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Hypothesis"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Hypothesis"> | Date | string
}

export type HypothesisCreateInput = {
  id?: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutHypothesesInput
  experiments?: Prisma.ExperimentCreateNestedManyWithoutHypothesisInput
}

export type HypothesisUncheckedCreateInput = {
  id?: string
  projectId: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  experiments?: Prisma.ExperimentUncheckedCreateNestedManyWithoutHypothesisInput
}

export type HypothesisUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutHypothesesNestedInput
  experiments?: Prisma.ExperimentUpdateManyWithoutHypothesisNestedInput
}

export type HypothesisUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiments?: Prisma.ExperimentUncheckedUpdateManyWithoutHypothesisNestedInput
}

export type HypothesisCreateManyInput = {
  id?: string
  projectId: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HypothesisUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HypothesisUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HypothesisListRelationFilter = {
  every?: Prisma.HypothesisWhereInput
  some?: Prisma.HypothesisWhereInput
  none?: Prisma.HypothesisWhereInput
}

export type HypothesisOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HypothesisCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  statement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  evidence?: Prisma.SortOrder
  basedOn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HypothesisMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  statement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HypothesisMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  statement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HypothesisNullableScalarRelationFilter = {
  is?: Prisma.HypothesisWhereInput | null
  isNot?: Prisma.HypothesisWhereInput | null
}

export type HypothesisCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.HypothesisCreateWithoutProjectInput, Prisma.HypothesisUncheckedCreateWithoutProjectInput> | Prisma.HypothesisCreateWithoutProjectInput[] | Prisma.HypothesisUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.HypothesisCreateOrConnectWithoutProjectInput | Prisma.HypothesisCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.HypothesisCreateManyProjectInputEnvelope
  connect?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
}

export type HypothesisUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.HypothesisCreateWithoutProjectInput, Prisma.HypothesisUncheckedCreateWithoutProjectInput> | Prisma.HypothesisCreateWithoutProjectInput[] | Prisma.HypothesisUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.HypothesisCreateOrConnectWithoutProjectInput | Prisma.HypothesisCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.HypothesisCreateManyProjectInputEnvelope
  connect?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
}

export type HypothesisUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.HypothesisCreateWithoutProjectInput, Prisma.HypothesisUncheckedCreateWithoutProjectInput> | Prisma.HypothesisCreateWithoutProjectInput[] | Prisma.HypothesisUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.HypothesisCreateOrConnectWithoutProjectInput | Prisma.HypothesisCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.HypothesisUpsertWithWhereUniqueWithoutProjectInput | Prisma.HypothesisUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.HypothesisCreateManyProjectInputEnvelope
  set?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  disconnect?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  delete?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  connect?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  update?: Prisma.HypothesisUpdateWithWhereUniqueWithoutProjectInput | Prisma.HypothesisUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.HypothesisUpdateManyWithWhereWithoutProjectInput | Prisma.HypothesisUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.HypothesisScalarWhereInput | Prisma.HypothesisScalarWhereInput[]
}

export type HypothesisUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.HypothesisCreateWithoutProjectInput, Prisma.HypothesisUncheckedCreateWithoutProjectInput> | Prisma.HypothesisCreateWithoutProjectInput[] | Prisma.HypothesisUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.HypothesisCreateOrConnectWithoutProjectInput | Prisma.HypothesisCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.HypothesisUpsertWithWhereUniqueWithoutProjectInput | Prisma.HypothesisUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.HypothesisCreateManyProjectInputEnvelope
  set?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  disconnect?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  delete?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  connect?: Prisma.HypothesisWhereUniqueInput | Prisma.HypothesisWhereUniqueInput[]
  update?: Prisma.HypothesisUpdateWithWhereUniqueWithoutProjectInput | Prisma.HypothesisUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.HypothesisUpdateManyWithWhereWithoutProjectInput | Prisma.HypothesisUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.HypothesisScalarWhereInput | Prisma.HypothesisScalarWhereInput[]
}

export type HypothesisCreatebasedOnInput = {
  set: string[]
}

export type HypothesisUpdatebasedOnInput = {
  set?: string[]
  push?: string | string[]
}

export type HypothesisCreateNestedOneWithoutExperimentsInput = {
  create?: Prisma.XOR<Prisma.HypothesisCreateWithoutExperimentsInput, Prisma.HypothesisUncheckedCreateWithoutExperimentsInput>
  connectOrCreate?: Prisma.HypothesisCreateOrConnectWithoutExperimentsInput
  connect?: Prisma.HypothesisWhereUniqueInput
}

export type HypothesisUpdateOneWithoutExperimentsNestedInput = {
  create?: Prisma.XOR<Prisma.HypothesisCreateWithoutExperimentsInput, Prisma.HypothesisUncheckedCreateWithoutExperimentsInput>
  connectOrCreate?: Prisma.HypothesisCreateOrConnectWithoutExperimentsInput
  upsert?: Prisma.HypothesisUpsertWithoutExperimentsInput
  disconnect?: Prisma.HypothesisWhereInput | boolean
  delete?: Prisma.HypothesisWhereInput | boolean
  connect?: Prisma.HypothesisWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HypothesisUpdateToOneWithWhereWithoutExperimentsInput, Prisma.HypothesisUpdateWithoutExperimentsInput>, Prisma.HypothesisUncheckedUpdateWithoutExperimentsInput>
}

export type HypothesisCreateWithoutProjectInput = {
  id?: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  experiments?: Prisma.ExperimentCreateNestedManyWithoutHypothesisInput
}

export type HypothesisUncheckedCreateWithoutProjectInput = {
  id?: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  experiments?: Prisma.ExperimentUncheckedCreateNestedManyWithoutHypothesisInput
}

export type HypothesisCreateOrConnectWithoutProjectInput = {
  where: Prisma.HypothesisWhereUniqueInput
  create: Prisma.XOR<Prisma.HypothesisCreateWithoutProjectInput, Prisma.HypothesisUncheckedCreateWithoutProjectInput>
}

export type HypothesisCreateManyProjectInputEnvelope = {
  data: Prisma.HypothesisCreateManyProjectInput | Prisma.HypothesisCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type HypothesisUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.HypothesisWhereUniqueInput
  update: Prisma.XOR<Prisma.HypothesisUpdateWithoutProjectInput, Prisma.HypothesisUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.HypothesisCreateWithoutProjectInput, Prisma.HypothesisUncheckedCreateWithoutProjectInput>
}

export type HypothesisUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.HypothesisWhereUniqueInput
  data: Prisma.XOR<Prisma.HypothesisUpdateWithoutProjectInput, Prisma.HypothesisUncheckedUpdateWithoutProjectInput>
}

export type HypothesisUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.HypothesisScalarWhereInput
  data: Prisma.XOR<Prisma.HypothesisUpdateManyMutationInput, Prisma.HypothesisUncheckedUpdateManyWithoutProjectInput>
}

export type HypothesisScalarWhereInput = {
  AND?: Prisma.HypothesisScalarWhereInput | Prisma.HypothesisScalarWhereInput[]
  OR?: Prisma.HypothesisScalarWhereInput[]
  NOT?: Prisma.HypothesisScalarWhereInput | Prisma.HypothesisScalarWhereInput[]
  id?: Prisma.StringFilter<"Hypothesis"> | string
  projectId?: Prisma.StringFilter<"Hypothesis"> | string
  statement?: Prisma.StringFilter<"Hypothesis"> | string
  status?: Prisma.StringFilter<"Hypothesis"> | string
  evidence?: Prisma.JsonNullableFilter<"Hypothesis">
  basedOn?: Prisma.StringNullableListFilter<"Hypothesis">
  createdAt?: Prisma.DateTimeFilter<"Hypothesis"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hypothesis"> | Date | string
}

export type HypothesisCreateWithoutExperimentsInput = {
  id?: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutHypothesesInput
}

export type HypothesisUncheckedCreateWithoutExperimentsInput = {
  id?: string
  projectId: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HypothesisCreateOrConnectWithoutExperimentsInput = {
  where: Prisma.HypothesisWhereUniqueInput
  create: Prisma.XOR<Prisma.HypothesisCreateWithoutExperimentsInput, Prisma.HypothesisUncheckedCreateWithoutExperimentsInput>
}

export type HypothesisUpsertWithoutExperimentsInput = {
  update: Prisma.XOR<Prisma.HypothesisUpdateWithoutExperimentsInput, Prisma.HypothesisUncheckedUpdateWithoutExperimentsInput>
  create: Prisma.XOR<Prisma.HypothesisCreateWithoutExperimentsInput, Prisma.HypothesisUncheckedCreateWithoutExperimentsInput>
  where?: Prisma.HypothesisWhereInput
}

export type HypothesisUpdateToOneWithWhereWithoutExperimentsInput = {
  where?: Prisma.HypothesisWhereInput
  data: Prisma.XOR<Prisma.HypothesisUpdateWithoutExperimentsInput, Prisma.HypothesisUncheckedUpdateWithoutExperimentsInput>
}

export type HypothesisUpdateWithoutExperimentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutHypothesesNestedInput
}

export type HypothesisUncheckedUpdateWithoutExperimentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HypothesisCreateManyProjectInput = {
  id?: string
  statement: string
  status: string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisCreatebasedOnInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HypothesisUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiments?: Prisma.ExperimentUpdateManyWithoutHypothesisNestedInput
}

export type HypothesisUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiments?: Prisma.ExperimentUncheckedUpdateManyWithoutHypothesisNestedInput
}

export type HypothesisUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  statement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  evidence?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  basedOn?: Prisma.HypothesisUpdatebasedOnInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type HypothesisCountOutputType
 */

export type HypothesisCountOutputType = {
  experiments: number
}

export type HypothesisCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experiments?: boolean | HypothesisCountOutputTypeCountExperimentsArgs
}

/**
 * HypothesisCountOutputType without action
 */
export type HypothesisCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HypothesisCountOutputType
   */
  select?: Prisma.HypothesisCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HypothesisCountOutputType without action
 */
export type HypothesisCountOutputTypeCountExperimentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExperimentWhereInput
}


export type HypothesisSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  statement?: boolean
  status?: boolean
  evidence?: boolean
  basedOn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  experiments?: boolean | Prisma.Hypothesis$experimentsArgs<ExtArgs>
  _count?: boolean | Prisma.HypothesisCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hypothesis"]>

export type HypothesisSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  statement?: boolean
  status?: boolean
  evidence?: boolean
  basedOn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hypothesis"]>

export type HypothesisSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  statement?: boolean
  status?: boolean
  evidence?: boolean
  basedOn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hypothesis"]>

export type HypothesisSelectScalar = {
  id?: boolean
  projectId?: boolean
  statement?: boolean
  status?: boolean
  evidence?: boolean
  basedOn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type HypothesisOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "statement" | "status" | "evidence" | "basedOn" | "createdAt" | "updatedAt", ExtArgs["result"]["hypothesis"]>
export type HypothesisInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  experiments?: boolean | Prisma.Hypothesis$experimentsArgs<ExtArgs>
  _count?: boolean | Prisma.HypothesisCountOutputTypeDefaultArgs<ExtArgs>
}
export type HypothesisIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type HypothesisIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $HypothesisPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Hypothesis"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    experiments: Prisma.$ExperimentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    statement: string
    status: string
    evidence: runtime.JsonValue | null
    basedOn: string[]
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["hypothesis"]>
  composites: {}
}

export type HypothesisGetPayload<S extends boolean | null | undefined | HypothesisDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HypothesisPayload, S>

export type HypothesisCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HypothesisFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HypothesisCountAggregateInputType | true
  }

export interface HypothesisDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Hypothesis'], meta: { name: 'Hypothesis' } }
  /**
   * Find zero or one Hypothesis that matches the filter.
   * @param {HypothesisFindUniqueArgs} args - Arguments to find a Hypothesis
   * @example
   * // Get one Hypothesis
   * const hypothesis = await prisma.hypothesis.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HypothesisFindUniqueArgs>(args: Prisma.SelectSubset<T, HypothesisFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hypothesis that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HypothesisFindUniqueOrThrowArgs} args - Arguments to find a Hypothesis
   * @example
   * // Get one Hypothesis
   * const hypothesis = await prisma.hypothesis.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HypothesisFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HypothesisFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hypothesis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisFindFirstArgs} args - Arguments to find a Hypothesis
   * @example
   * // Get one Hypothesis
   * const hypothesis = await prisma.hypothesis.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HypothesisFindFirstArgs>(args?: Prisma.SelectSubset<T, HypothesisFindFirstArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hypothesis that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisFindFirstOrThrowArgs} args - Arguments to find a Hypothesis
   * @example
   * // Get one Hypothesis
   * const hypothesis = await prisma.hypothesis.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HypothesisFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HypothesisFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Hypotheses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Hypotheses
   * const hypotheses = await prisma.hypothesis.findMany()
   * 
   * // Get first 10 Hypotheses
   * const hypotheses = await prisma.hypothesis.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const hypothesisWithIdOnly = await prisma.hypothesis.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HypothesisFindManyArgs>(args?: Prisma.SelectSubset<T, HypothesisFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hypothesis.
   * @param {HypothesisCreateArgs} args - Arguments to create a Hypothesis.
   * @example
   * // Create one Hypothesis
   * const Hypothesis = await prisma.hypothesis.create({
   *   data: {
   *     // ... data to create a Hypothesis
   *   }
   * })
   * 
   */
  create<T extends HypothesisCreateArgs>(args: Prisma.SelectSubset<T, HypothesisCreateArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Hypotheses.
   * @param {HypothesisCreateManyArgs} args - Arguments to create many Hypotheses.
   * @example
   * // Create many Hypotheses
   * const hypothesis = await prisma.hypothesis.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HypothesisCreateManyArgs>(args?: Prisma.SelectSubset<T, HypothesisCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Hypotheses and returns the data saved in the database.
   * @param {HypothesisCreateManyAndReturnArgs} args - Arguments to create many Hypotheses.
   * @example
   * // Create many Hypotheses
   * const hypothesis = await prisma.hypothesis.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Hypotheses and only return the `id`
   * const hypothesisWithIdOnly = await prisma.hypothesis.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HypothesisCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HypothesisCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Hypothesis.
   * @param {HypothesisDeleteArgs} args - Arguments to delete one Hypothesis.
   * @example
   * // Delete one Hypothesis
   * const Hypothesis = await prisma.hypothesis.delete({
   *   where: {
   *     // ... filter to delete one Hypothesis
   *   }
   * })
   * 
   */
  delete<T extends HypothesisDeleteArgs>(args: Prisma.SelectSubset<T, HypothesisDeleteArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hypothesis.
   * @param {HypothesisUpdateArgs} args - Arguments to update one Hypothesis.
   * @example
   * // Update one Hypothesis
   * const hypothesis = await prisma.hypothesis.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HypothesisUpdateArgs>(args: Prisma.SelectSubset<T, HypothesisUpdateArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Hypotheses.
   * @param {HypothesisDeleteManyArgs} args - Arguments to filter Hypotheses to delete.
   * @example
   * // Delete a few Hypotheses
   * const { count } = await prisma.hypothesis.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HypothesisDeleteManyArgs>(args?: Prisma.SelectSubset<T, HypothesisDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hypotheses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Hypotheses
   * const hypothesis = await prisma.hypothesis.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HypothesisUpdateManyArgs>(args: Prisma.SelectSubset<T, HypothesisUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hypotheses and returns the data updated in the database.
   * @param {HypothesisUpdateManyAndReturnArgs} args - Arguments to update many Hypotheses.
   * @example
   * // Update many Hypotheses
   * const hypothesis = await prisma.hypothesis.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Hypotheses and only return the `id`
   * const hypothesisWithIdOnly = await prisma.hypothesis.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HypothesisUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HypothesisUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Hypothesis.
   * @param {HypothesisUpsertArgs} args - Arguments to update or create a Hypothesis.
   * @example
   * // Update or create a Hypothesis
   * const hypothesis = await prisma.hypothesis.upsert({
   *   create: {
   *     // ... data to create a Hypothesis
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hypothesis we want to update
   *   }
   * })
   */
  upsert<T extends HypothesisUpsertArgs>(args: Prisma.SelectSubset<T, HypothesisUpsertArgs<ExtArgs>>): Prisma.Prisma__HypothesisClient<runtime.Types.Result.GetResult<Prisma.$HypothesisPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Hypotheses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisCountArgs} args - Arguments to filter Hypotheses to count.
   * @example
   * // Count the number of Hypotheses
   * const count = await prisma.hypothesis.count({
   *   where: {
   *     // ... the filter for the Hypotheses we want to count
   *   }
   * })
  **/
  count<T extends HypothesisCountArgs>(
    args?: Prisma.Subset<T, HypothesisCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HypothesisCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hypothesis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HypothesisAggregateArgs>(args: Prisma.Subset<T, HypothesisAggregateArgs>): Prisma.PrismaPromise<GetHypothesisAggregateType<T>>

  /**
   * Group by Hypothesis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HypothesisGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HypothesisGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HypothesisGroupByArgs['orderBy'] }
      : { orderBy?: HypothesisGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HypothesisGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHypothesisGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Hypothesis model
 */
readonly fields: HypothesisFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Hypothesis.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HypothesisClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  experiments<T extends Prisma.Hypothesis$experimentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hypothesis$experimentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperimentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Hypothesis model
 */
export interface HypothesisFieldRefs {
  readonly id: Prisma.FieldRef<"Hypothesis", 'String'>
  readonly projectId: Prisma.FieldRef<"Hypothesis", 'String'>
  readonly statement: Prisma.FieldRef<"Hypothesis", 'String'>
  readonly status: Prisma.FieldRef<"Hypothesis", 'String'>
  readonly evidence: Prisma.FieldRef<"Hypothesis", 'Json'>
  readonly basedOn: Prisma.FieldRef<"Hypothesis", 'String[]'>
  readonly createdAt: Prisma.FieldRef<"Hypothesis", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Hypothesis", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Hypothesis findUnique
 */
export type HypothesisFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * Filter, which Hypothesis to fetch.
   */
  where: Prisma.HypothesisWhereUniqueInput
}

/**
 * Hypothesis findUniqueOrThrow
 */
export type HypothesisFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * Filter, which Hypothesis to fetch.
   */
  where: Prisma.HypothesisWhereUniqueInput
}

/**
 * Hypothesis findFirst
 */
export type HypothesisFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * Filter, which Hypothesis to fetch.
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hypotheses to fetch.
   */
  orderBy?: Prisma.HypothesisOrderByWithRelationInput | Prisma.HypothesisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Hypotheses.
   */
  cursor?: Prisma.HypothesisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hypotheses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hypotheses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hypotheses.
   */
  distinct?: Prisma.HypothesisScalarFieldEnum | Prisma.HypothesisScalarFieldEnum[]
}

/**
 * Hypothesis findFirstOrThrow
 */
export type HypothesisFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * Filter, which Hypothesis to fetch.
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hypotheses to fetch.
   */
  orderBy?: Prisma.HypothesisOrderByWithRelationInput | Prisma.HypothesisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Hypotheses.
   */
  cursor?: Prisma.HypothesisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hypotheses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hypotheses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hypotheses.
   */
  distinct?: Prisma.HypothesisScalarFieldEnum | Prisma.HypothesisScalarFieldEnum[]
}

/**
 * Hypothesis findMany
 */
export type HypothesisFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * Filter, which Hypotheses to fetch.
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hypotheses to fetch.
   */
  orderBy?: Prisma.HypothesisOrderByWithRelationInput | Prisma.HypothesisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Hypotheses.
   */
  cursor?: Prisma.HypothesisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hypotheses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hypotheses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hypotheses.
   */
  distinct?: Prisma.HypothesisScalarFieldEnum | Prisma.HypothesisScalarFieldEnum[]
}

/**
 * Hypothesis create
 */
export type HypothesisCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * The data needed to create a Hypothesis.
   */
  data: Prisma.XOR<Prisma.HypothesisCreateInput, Prisma.HypothesisUncheckedCreateInput>
}

/**
 * Hypothesis createMany
 */
export type HypothesisCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Hypotheses.
   */
  data: Prisma.HypothesisCreateManyInput | Prisma.HypothesisCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Hypothesis createManyAndReturn
 */
export type HypothesisCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * The data used to create many Hypotheses.
   */
  data: Prisma.HypothesisCreateManyInput | Prisma.HypothesisCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Hypothesis update
 */
export type HypothesisUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * The data needed to update a Hypothesis.
   */
  data: Prisma.XOR<Prisma.HypothesisUpdateInput, Prisma.HypothesisUncheckedUpdateInput>
  /**
   * Choose, which Hypothesis to update.
   */
  where: Prisma.HypothesisWhereUniqueInput
}

/**
 * Hypothesis updateMany
 */
export type HypothesisUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Hypotheses.
   */
  data: Prisma.XOR<Prisma.HypothesisUpdateManyMutationInput, Prisma.HypothesisUncheckedUpdateManyInput>
  /**
   * Filter which Hypotheses to update
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * Limit how many Hypotheses to update.
   */
  limit?: number
}

/**
 * Hypothesis updateManyAndReturn
 */
export type HypothesisUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * The data used to update Hypotheses.
   */
  data: Prisma.XOR<Prisma.HypothesisUpdateManyMutationInput, Prisma.HypothesisUncheckedUpdateManyInput>
  /**
   * Filter which Hypotheses to update
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * Limit how many Hypotheses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Hypothesis upsert
 */
export type HypothesisUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * The filter to search for the Hypothesis to update in case it exists.
   */
  where: Prisma.HypothesisWhereUniqueInput
  /**
   * In case the Hypothesis found by the `where` argument doesn't exist, create a new Hypothesis with this data.
   */
  create: Prisma.XOR<Prisma.HypothesisCreateInput, Prisma.HypothesisUncheckedCreateInput>
  /**
   * In case the Hypothesis was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HypothesisUpdateInput, Prisma.HypothesisUncheckedUpdateInput>
}

/**
 * Hypothesis delete
 */
export type HypothesisDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
  /**
   * Filter which Hypothesis to delete.
   */
  where: Prisma.HypothesisWhereUniqueInput
}

/**
 * Hypothesis deleteMany
 */
export type HypothesisDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hypotheses to delete
   */
  where?: Prisma.HypothesisWhereInput
  /**
   * Limit how many Hypotheses to delete.
   */
  limit?: number
}

/**
 * Hypothesis.experiments
 */
export type Hypothesis$experimentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Experiment
   */
  select?: Prisma.ExperimentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Experiment
   */
  omit?: Prisma.ExperimentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperimentInclude<ExtArgs> | null
  where?: Prisma.ExperimentWhereInput
  orderBy?: Prisma.ExperimentOrderByWithRelationInput | Prisma.ExperimentOrderByWithRelationInput[]
  cursor?: Prisma.ExperimentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExperimentScalarFieldEnum | Prisma.ExperimentScalarFieldEnum[]
}

/**
 * Hypothesis without action
 */
export type HypothesisDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hypothesis
   */
  select?: Prisma.HypothesisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hypothesis
   */
  omit?: Prisma.HypothesisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HypothesisInclude<ExtArgs> | null
}
