
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Manuscript` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Manuscript
 * 
 */
export type ManuscriptModel = runtime.Types.Result.DefaultSelection<Prisma.$ManuscriptPayload>

export type AggregateManuscript = {
  _count: ManuscriptCountAggregateOutputType | null
  _min: ManuscriptMinAggregateOutputType | null
  _max: ManuscriptMaxAggregateOutputType | null
}

export type ManuscriptMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  journal: string | null
  language: string | null
  abstract: string | null
  introduction: string | null
  methods: string | null
  results: string | null
  discussion: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ManuscriptMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  journal: string | null
  language: string | null
  abstract: string | null
  introduction: string | null
  methods: string | null
  results: string | null
  discussion: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ManuscriptCountAggregateOutputType = {
  id: number
  projectId: number
  journal: number
  language: number
  abstract: number
  introduction: number
  methods: number
  results: number
  discussion: number
  references: number
  reviewSimulation: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ManuscriptMinAggregateInputType = {
  id?: true
  projectId?: true
  journal?: true
  language?: true
  abstract?: true
  introduction?: true
  methods?: true
  results?: true
  discussion?: true
  createdAt?: true
  updatedAt?: true
}

export type ManuscriptMaxAggregateInputType = {
  id?: true
  projectId?: true
  journal?: true
  language?: true
  abstract?: true
  introduction?: true
  methods?: true
  results?: true
  discussion?: true
  createdAt?: true
  updatedAt?: true
}

export type ManuscriptCountAggregateInputType = {
  id?: true
  projectId?: true
  journal?: true
  language?: true
  abstract?: true
  introduction?: true
  methods?: true
  results?: true
  discussion?: true
  references?: true
  reviewSimulation?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ManuscriptAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Manuscript to aggregate.
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manuscripts to fetch.
   */
  orderBy?: Prisma.ManuscriptOrderByWithRelationInput | Prisma.ManuscriptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ManuscriptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manuscripts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manuscripts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Manuscripts
  **/
  _count?: true | ManuscriptCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ManuscriptMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ManuscriptMaxAggregateInputType
}

export type GetManuscriptAggregateType<T extends ManuscriptAggregateArgs> = {
      [P in keyof T & keyof AggregateManuscript]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateManuscript[P]>
    : Prisma.GetScalarType<T[P], AggregateManuscript[P]>
}




export type ManuscriptGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManuscriptWhereInput
  orderBy?: Prisma.ManuscriptOrderByWithAggregationInput | Prisma.ManuscriptOrderByWithAggregationInput[]
  by: Prisma.ManuscriptScalarFieldEnum[] | Prisma.ManuscriptScalarFieldEnum
  having?: Prisma.ManuscriptScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ManuscriptCountAggregateInputType | true
  _min?: ManuscriptMinAggregateInputType
  _max?: ManuscriptMaxAggregateInputType
}

export type ManuscriptGroupByOutputType = {
  id: string
  projectId: string
  journal: string | null
  language: string
  abstract: string | null
  introduction: string | null
  methods: string | null
  results: string | null
  discussion: string | null
  references: runtime.JsonValue | null
  reviewSimulation: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: ManuscriptCountAggregateOutputType | null
  _min: ManuscriptMinAggregateOutputType | null
  _max: ManuscriptMaxAggregateOutputType | null
}

export type GetManuscriptGroupByPayload<T extends ManuscriptGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ManuscriptGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ManuscriptGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ManuscriptGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ManuscriptGroupByOutputType[P]>
      }
    >
  >



export type ManuscriptWhereInput = {
  AND?: Prisma.ManuscriptWhereInput | Prisma.ManuscriptWhereInput[]
  OR?: Prisma.ManuscriptWhereInput[]
  NOT?: Prisma.ManuscriptWhereInput | Prisma.ManuscriptWhereInput[]
  id?: Prisma.StringFilter<"Manuscript"> | string
  projectId?: Prisma.StringFilter<"Manuscript"> | string
  journal?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  language?: Prisma.StringFilter<"Manuscript"> | string
  abstract?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  introduction?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  methods?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  results?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  discussion?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  references?: Prisma.JsonNullableFilter<"Manuscript">
  reviewSimulation?: Prisma.JsonNullableFilter<"Manuscript">
  createdAt?: Prisma.DateTimeFilter<"Manuscript"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Manuscript"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type ManuscriptOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  journal?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrder
  abstract?: Prisma.SortOrderInput | Prisma.SortOrder
  introduction?: Prisma.SortOrderInput | Prisma.SortOrder
  methods?: Prisma.SortOrderInput | Prisma.SortOrder
  results?: Prisma.SortOrderInput | Prisma.SortOrder
  discussion?: Prisma.SortOrderInput | Prisma.SortOrder
  references?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewSimulation?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type ManuscriptWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ManuscriptWhereInput | Prisma.ManuscriptWhereInput[]
  OR?: Prisma.ManuscriptWhereInput[]
  NOT?: Prisma.ManuscriptWhereInput | Prisma.ManuscriptWhereInput[]
  projectId?: Prisma.StringFilter<"Manuscript"> | string
  journal?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  language?: Prisma.StringFilter<"Manuscript"> | string
  abstract?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  introduction?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  methods?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  results?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  discussion?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  references?: Prisma.JsonNullableFilter<"Manuscript">
  reviewSimulation?: Prisma.JsonNullableFilter<"Manuscript">
  createdAt?: Prisma.DateTimeFilter<"Manuscript"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Manuscript"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id">

export type ManuscriptOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  journal?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrder
  abstract?: Prisma.SortOrderInput | Prisma.SortOrder
  introduction?: Prisma.SortOrderInput | Prisma.SortOrder
  methods?: Prisma.SortOrderInput | Prisma.SortOrder
  results?: Prisma.SortOrderInput | Prisma.SortOrder
  discussion?: Prisma.SortOrderInput | Prisma.SortOrder
  references?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewSimulation?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ManuscriptCountOrderByAggregateInput
  _max?: Prisma.ManuscriptMaxOrderByAggregateInput
  _min?: Prisma.ManuscriptMinOrderByAggregateInput
}

export type ManuscriptScalarWhereWithAggregatesInput = {
  AND?: Prisma.ManuscriptScalarWhereWithAggregatesInput | Prisma.ManuscriptScalarWhereWithAggregatesInput[]
  OR?: Prisma.ManuscriptScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ManuscriptScalarWhereWithAggregatesInput | Prisma.ManuscriptScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Manuscript"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Manuscript"> | string
  journal?: Prisma.StringNullableWithAggregatesFilter<"Manuscript"> | string | null
  language?: Prisma.StringWithAggregatesFilter<"Manuscript"> | string
  abstract?: Prisma.StringNullableWithAggregatesFilter<"Manuscript"> | string | null
  introduction?: Prisma.StringNullableWithAggregatesFilter<"Manuscript"> | string | null
  methods?: Prisma.StringNullableWithAggregatesFilter<"Manuscript"> | string | null
  results?: Prisma.StringNullableWithAggregatesFilter<"Manuscript"> | string | null
  discussion?: Prisma.StringNullableWithAggregatesFilter<"Manuscript"> | string | null
  references?: Prisma.JsonNullableWithAggregatesFilter<"Manuscript">
  reviewSimulation?: Prisma.JsonNullableWithAggregatesFilter<"Manuscript">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Manuscript"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Manuscript"> | Date | string
}

export type ManuscriptCreateInput = {
  id?: string
  journal?: string | null
  language?: string
  abstract?: string | null
  introduction?: string | null
  methods?: string | null
  results?: string | null
  discussion?: string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutManuscriptsInput
}

export type ManuscriptUncheckedCreateInput = {
  id?: string
  projectId: string
  journal?: string | null
  language?: string
  abstract?: string | null
  introduction?: string | null
  methods?: string | null
  results?: string | null
  discussion?: string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManuscriptUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutManuscriptsNestedInput
}

export type ManuscriptUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManuscriptCreateManyInput = {
  id?: string
  projectId: string
  journal?: string | null
  language?: string
  abstract?: string | null
  introduction?: string | null
  methods?: string | null
  results?: string | null
  discussion?: string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManuscriptUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManuscriptUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManuscriptListRelationFilter = {
  every?: Prisma.ManuscriptWhereInput
  some?: Prisma.ManuscriptWhereInput
  none?: Prisma.ManuscriptWhereInput
}

export type ManuscriptOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ManuscriptCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  language?: Prisma.SortOrder
  abstract?: Prisma.SortOrder
  introduction?: Prisma.SortOrder
  methods?: Prisma.SortOrder
  results?: Prisma.SortOrder
  discussion?: Prisma.SortOrder
  references?: Prisma.SortOrder
  reviewSimulation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManuscriptMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  language?: Prisma.SortOrder
  abstract?: Prisma.SortOrder
  introduction?: Prisma.SortOrder
  methods?: Prisma.SortOrder
  results?: Prisma.SortOrder
  discussion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManuscriptMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  language?: Prisma.SortOrder
  abstract?: Prisma.SortOrder
  introduction?: Prisma.SortOrder
  methods?: Prisma.SortOrder
  results?: Prisma.SortOrder
  discussion?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManuscriptCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ManuscriptCreateWithoutProjectInput, Prisma.ManuscriptUncheckedCreateWithoutProjectInput> | Prisma.ManuscriptCreateWithoutProjectInput[] | Prisma.ManuscriptUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ManuscriptCreateOrConnectWithoutProjectInput | Prisma.ManuscriptCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ManuscriptCreateManyProjectInputEnvelope
  connect?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
}

export type ManuscriptUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ManuscriptCreateWithoutProjectInput, Prisma.ManuscriptUncheckedCreateWithoutProjectInput> | Prisma.ManuscriptCreateWithoutProjectInput[] | Prisma.ManuscriptUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ManuscriptCreateOrConnectWithoutProjectInput | Prisma.ManuscriptCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ManuscriptCreateManyProjectInputEnvelope
  connect?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
}

export type ManuscriptUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ManuscriptCreateWithoutProjectInput, Prisma.ManuscriptUncheckedCreateWithoutProjectInput> | Prisma.ManuscriptCreateWithoutProjectInput[] | Prisma.ManuscriptUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ManuscriptCreateOrConnectWithoutProjectInput | Prisma.ManuscriptCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ManuscriptUpsertWithWhereUniqueWithoutProjectInput | Prisma.ManuscriptUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ManuscriptCreateManyProjectInputEnvelope
  set?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  disconnect?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  delete?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  connect?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  update?: Prisma.ManuscriptUpdateWithWhereUniqueWithoutProjectInput | Prisma.ManuscriptUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ManuscriptUpdateManyWithWhereWithoutProjectInput | Prisma.ManuscriptUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ManuscriptScalarWhereInput | Prisma.ManuscriptScalarWhereInput[]
}

export type ManuscriptUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ManuscriptCreateWithoutProjectInput, Prisma.ManuscriptUncheckedCreateWithoutProjectInput> | Prisma.ManuscriptCreateWithoutProjectInput[] | Prisma.ManuscriptUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ManuscriptCreateOrConnectWithoutProjectInput | Prisma.ManuscriptCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ManuscriptUpsertWithWhereUniqueWithoutProjectInput | Prisma.ManuscriptUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ManuscriptCreateManyProjectInputEnvelope
  set?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  disconnect?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  delete?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  connect?: Prisma.ManuscriptWhereUniqueInput | Prisma.ManuscriptWhereUniqueInput[]
  update?: Prisma.ManuscriptUpdateWithWhereUniqueWithoutProjectInput | Prisma.ManuscriptUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ManuscriptUpdateManyWithWhereWithoutProjectInput | Prisma.ManuscriptUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ManuscriptScalarWhereInput | Prisma.ManuscriptScalarWhereInput[]
}

export type ManuscriptCreateWithoutProjectInput = {
  id?: string
  journal?: string | null
  language?: string
  abstract?: string | null
  introduction?: string | null
  methods?: string | null
  results?: string | null
  discussion?: string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManuscriptUncheckedCreateWithoutProjectInput = {
  id?: string
  journal?: string | null
  language?: string
  abstract?: string | null
  introduction?: string | null
  methods?: string | null
  results?: string | null
  discussion?: string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManuscriptCreateOrConnectWithoutProjectInput = {
  where: Prisma.ManuscriptWhereUniqueInput
  create: Prisma.XOR<Prisma.ManuscriptCreateWithoutProjectInput, Prisma.ManuscriptUncheckedCreateWithoutProjectInput>
}

export type ManuscriptCreateManyProjectInputEnvelope = {
  data: Prisma.ManuscriptCreateManyProjectInput | Prisma.ManuscriptCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type ManuscriptUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ManuscriptWhereUniqueInput
  update: Prisma.XOR<Prisma.ManuscriptUpdateWithoutProjectInput, Prisma.ManuscriptUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ManuscriptCreateWithoutProjectInput, Prisma.ManuscriptUncheckedCreateWithoutProjectInput>
}

export type ManuscriptUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ManuscriptWhereUniqueInput
  data: Prisma.XOR<Prisma.ManuscriptUpdateWithoutProjectInput, Prisma.ManuscriptUncheckedUpdateWithoutProjectInput>
}

export type ManuscriptUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ManuscriptScalarWhereInput
  data: Prisma.XOR<Prisma.ManuscriptUpdateManyMutationInput, Prisma.ManuscriptUncheckedUpdateManyWithoutProjectInput>
}

export type ManuscriptScalarWhereInput = {
  AND?: Prisma.ManuscriptScalarWhereInput | Prisma.ManuscriptScalarWhereInput[]
  OR?: Prisma.ManuscriptScalarWhereInput[]
  NOT?: Prisma.ManuscriptScalarWhereInput | Prisma.ManuscriptScalarWhereInput[]
  id?: Prisma.StringFilter<"Manuscript"> | string
  projectId?: Prisma.StringFilter<"Manuscript"> | string
  journal?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  language?: Prisma.StringFilter<"Manuscript"> | string
  abstract?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  introduction?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  methods?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  results?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  discussion?: Prisma.StringNullableFilter<"Manuscript"> | string | null
  references?: Prisma.JsonNullableFilter<"Manuscript">
  reviewSimulation?: Prisma.JsonNullableFilter<"Manuscript">
  createdAt?: Prisma.DateTimeFilter<"Manuscript"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Manuscript"> | Date | string
}

export type ManuscriptCreateManyProjectInput = {
  id?: string
  journal?: string | null
  language?: string
  abstract?: string | null
  introduction?: string | null
  methods?: string | null
  results?: string | null
  discussion?: string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManuscriptUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManuscriptUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManuscriptUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  introduction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  methods?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  results?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discussion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  references?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  reviewSimulation?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ManuscriptSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  journal?: boolean
  language?: boolean
  abstract?: boolean
  introduction?: boolean
  methods?: boolean
  results?: boolean
  discussion?: boolean
  references?: boolean
  reviewSimulation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manuscript"]>

export type ManuscriptSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  journal?: boolean
  language?: boolean
  abstract?: boolean
  introduction?: boolean
  methods?: boolean
  results?: boolean
  discussion?: boolean
  references?: boolean
  reviewSimulation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manuscript"]>

export type ManuscriptSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  journal?: boolean
  language?: boolean
  abstract?: boolean
  introduction?: boolean
  methods?: boolean
  results?: boolean
  discussion?: boolean
  references?: boolean
  reviewSimulation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manuscript"]>

export type ManuscriptSelectScalar = {
  id?: boolean
  projectId?: boolean
  journal?: boolean
  language?: boolean
  abstract?: boolean
  introduction?: boolean
  methods?: boolean
  results?: boolean
  discussion?: boolean
  references?: boolean
  reviewSimulation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ManuscriptOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "journal" | "language" | "abstract" | "introduction" | "methods" | "results" | "discussion" | "references" | "reviewSimulation" | "createdAt" | "updatedAt", ExtArgs["result"]["manuscript"]>
export type ManuscriptInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ManuscriptIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type ManuscriptIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $ManuscriptPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Manuscript"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    journal: string | null
    language: string
    abstract: string | null
    introduction: string | null
    methods: string | null
    results: string | null
    discussion: string | null
    references: runtime.JsonValue | null
    reviewSimulation: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["manuscript"]>
  composites: {}
}

export type ManuscriptGetPayload<S extends boolean | null | undefined | ManuscriptDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload, S>

export type ManuscriptCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ManuscriptFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ManuscriptCountAggregateInputType | true
  }

export interface ManuscriptDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Manuscript'], meta: { name: 'Manuscript' } }
  /**
   * Find zero or one Manuscript that matches the filter.
   * @param {ManuscriptFindUniqueArgs} args - Arguments to find a Manuscript
   * @example
   * // Get one Manuscript
   * const manuscript = await prisma.manuscript.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ManuscriptFindUniqueArgs>(args: Prisma.SelectSubset<T, ManuscriptFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Manuscript that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ManuscriptFindUniqueOrThrowArgs} args - Arguments to find a Manuscript
   * @example
   * // Get one Manuscript
   * const manuscript = await prisma.manuscript.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ManuscriptFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ManuscriptFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Manuscript that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptFindFirstArgs} args - Arguments to find a Manuscript
   * @example
   * // Get one Manuscript
   * const manuscript = await prisma.manuscript.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ManuscriptFindFirstArgs>(args?: Prisma.SelectSubset<T, ManuscriptFindFirstArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Manuscript that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptFindFirstOrThrowArgs} args - Arguments to find a Manuscript
   * @example
   * // Get one Manuscript
   * const manuscript = await prisma.manuscript.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ManuscriptFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ManuscriptFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Manuscripts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Manuscripts
   * const manuscripts = await prisma.manuscript.findMany()
   * 
   * // Get first 10 Manuscripts
   * const manuscripts = await prisma.manuscript.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const manuscriptWithIdOnly = await prisma.manuscript.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ManuscriptFindManyArgs>(args?: Prisma.SelectSubset<T, ManuscriptFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Manuscript.
   * @param {ManuscriptCreateArgs} args - Arguments to create a Manuscript.
   * @example
   * // Create one Manuscript
   * const Manuscript = await prisma.manuscript.create({
   *   data: {
   *     // ... data to create a Manuscript
   *   }
   * })
   * 
   */
  create<T extends ManuscriptCreateArgs>(args: Prisma.SelectSubset<T, ManuscriptCreateArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Manuscripts.
   * @param {ManuscriptCreateManyArgs} args - Arguments to create many Manuscripts.
   * @example
   * // Create many Manuscripts
   * const manuscript = await prisma.manuscript.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ManuscriptCreateManyArgs>(args?: Prisma.SelectSubset<T, ManuscriptCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Manuscripts and returns the data saved in the database.
   * @param {ManuscriptCreateManyAndReturnArgs} args - Arguments to create many Manuscripts.
   * @example
   * // Create many Manuscripts
   * const manuscript = await prisma.manuscript.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Manuscripts and only return the `id`
   * const manuscriptWithIdOnly = await prisma.manuscript.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ManuscriptCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ManuscriptCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Manuscript.
   * @param {ManuscriptDeleteArgs} args - Arguments to delete one Manuscript.
   * @example
   * // Delete one Manuscript
   * const Manuscript = await prisma.manuscript.delete({
   *   where: {
   *     // ... filter to delete one Manuscript
   *   }
   * })
   * 
   */
  delete<T extends ManuscriptDeleteArgs>(args: Prisma.SelectSubset<T, ManuscriptDeleteArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Manuscript.
   * @param {ManuscriptUpdateArgs} args - Arguments to update one Manuscript.
   * @example
   * // Update one Manuscript
   * const manuscript = await prisma.manuscript.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ManuscriptUpdateArgs>(args: Prisma.SelectSubset<T, ManuscriptUpdateArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Manuscripts.
   * @param {ManuscriptDeleteManyArgs} args - Arguments to filter Manuscripts to delete.
   * @example
   * // Delete a few Manuscripts
   * const { count } = await prisma.manuscript.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ManuscriptDeleteManyArgs>(args?: Prisma.SelectSubset<T, ManuscriptDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Manuscripts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Manuscripts
   * const manuscript = await prisma.manuscript.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ManuscriptUpdateManyArgs>(args: Prisma.SelectSubset<T, ManuscriptUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Manuscripts and returns the data updated in the database.
   * @param {ManuscriptUpdateManyAndReturnArgs} args - Arguments to update many Manuscripts.
   * @example
   * // Update many Manuscripts
   * const manuscript = await prisma.manuscript.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Manuscripts and only return the `id`
   * const manuscriptWithIdOnly = await prisma.manuscript.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ManuscriptUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ManuscriptUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Manuscript.
   * @param {ManuscriptUpsertArgs} args - Arguments to update or create a Manuscript.
   * @example
   * // Update or create a Manuscript
   * const manuscript = await prisma.manuscript.upsert({
   *   create: {
   *     // ... data to create a Manuscript
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Manuscript we want to update
   *   }
   * })
   */
  upsert<T extends ManuscriptUpsertArgs>(args: Prisma.SelectSubset<T, ManuscriptUpsertArgs<ExtArgs>>): Prisma.Prisma__ManuscriptClient<runtime.Types.Result.GetResult<Prisma.$ManuscriptPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Manuscripts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptCountArgs} args - Arguments to filter Manuscripts to count.
   * @example
   * // Count the number of Manuscripts
   * const count = await prisma.manuscript.count({
   *   where: {
   *     // ... the filter for the Manuscripts we want to count
   *   }
   * })
  **/
  count<T extends ManuscriptCountArgs>(
    args?: Prisma.Subset<T, ManuscriptCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ManuscriptCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Manuscript.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ManuscriptAggregateArgs>(args: Prisma.Subset<T, ManuscriptAggregateArgs>): Prisma.PrismaPromise<GetManuscriptAggregateType<T>>

  /**
   * Group by Manuscript.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManuscriptGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ManuscriptGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ManuscriptGroupByArgs['orderBy'] }
      : { orderBy?: ManuscriptGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ManuscriptGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetManuscriptGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Manuscript model
 */
readonly fields: ManuscriptFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Manuscript.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ManuscriptClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Manuscript model
 */
export interface ManuscriptFieldRefs {
  readonly id: Prisma.FieldRef<"Manuscript", 'String'>
  readonly projectId: Prisma.FieldRef<"Manuscript", 'String'>
  readonly journal: Prisma.FieldRef<"Manuscript", 'String'>
  readonly language: Prisma.FieldRef<"Manuscript", 'String'>
  readonly abstract: Prisma.FieldRef<"Manuscript", 'String'>
  readonly introduction: Prisma.FieldRef<"Manuscript", 'String'>
  readonly methods: Prisma.FieldRef<"Manuscript", 'String'>
  readonly results: Prisma.FieldRef<"Manuscript", 'String'>
  readonly discussion: Prisma.FieldRef<"Manuscript", 'String'>
  readonly references: Prisma.FieldRef<"Manuscript", 'Json'>
  readonly reviewSimulation: Prisma.FieldRef<"Manuscript", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Manuscript", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Manuscript", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Manuscript findUnique
 */
export type ManuscriptFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * Filter, which Manuscript to fetch.
   */
  where: Prisma.ManuscriptWhereUniqueInput
}

/**
 * Manuscript findUniqueOrThrow
 */
export type ManuscriptFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * Filter, which Manuscript to fetch.
   */
  where: Prisma.ManuscriptWhereUniqueInput
}

/**
 * Manuscript findFirst
 */
export type ManuscriptFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * Filter, which Manuscript to fetch.
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manuscripts to fetch.
   */
  orderBy?: Prisma.ManuscriptOrderByWithRelationInput | Prisma.ManuscriptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Manuscripts.
   */
  cursor?: Prisma.ManuscriptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manuscripts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manuscripts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Manuscripts.
   */
  distinct?: Prisma.ManuscriptScalarFieldEnum | Prisma.ManuscriptScalarFieldEnum[]
}

/**
 * Manuscript findFirstOrThrow
 */
export type ManuscriptFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * Filter, which Manuscript to fetch.
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manuscripts to fetch.
   */
  orderBy?: Prisma.ManuscriptOrderByWithRelationInput | Prisma.ManuscriptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Manuscripts.
   */
  cursor?: Prisma.ManuscriptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manuscripts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manuscripts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Manuscripts.
   */
  distinct?: Prisma.ManuscriptScalarFieldEnum | Prisma.ManuscriptScalarFieldEnum[]
}

/**
 * Manuscript findMany
 */
export type ManuscriptFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * Filter, which Manuscripts to fetch.
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manuscripts to fetch.
   */
  orderBy?: Prisma.ManuscriptOrderByWithRelationInput | Prisma.ManuscriptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Manuscripts.
   */
  cursor?: Prisma.ManuscriptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manuscripts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manuscripts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Manuscripts.
   */
  distinct?: Prisma.ManuscriptScalarFieldEnum | Prisma.ManuscriptScalarFieldEnum[]
}

/**
 * Manuscript create
 */
export type ManuscriptCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * The data needed to create a Manuscript.
   */
  data: Prisma.XOR<Prisma.ManuscriptCreateInput, Prisma.ManuscriptUncheckedCreateInput>
}

/**
 * Manuscript createMany
 */
export type ManuscriptCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Manuscripts.
   */
  data: Prisma.ManuscriptCreateManyInput | Prisma.ManuscriptCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Manuscript createManyAndReturn
 */
export type ManuscriptCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * The data used to create many Manuscripts.
   */
  data: Prisma.ManuscriptCreateManyInput | Prisma.ManuscriptCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Manuscript update
 */
export type ManuscriptUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * The data needed to update a Manuscript.
   */
  data: Prisma.XOR<Prisma.ManuscriptUpdateInput, Prisma.ManuscriptUncheckedUpdateInput>
  /**
   * Choose, which Manuscript to update.
   */
  where: Prisma.ManuscriptWhereUniqueInput
}

/**
 * Manuscript updateMany
 */
export type ManuscriptUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Manuscripts.
   */
  data: Prisma.XOR<Prisma.ManuscriptUpdateManyMutationInput, Prisma.ManuscriptUncheckedUpdateManyInput>
  /**
   * Filter which Manuscripts to update
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * Limit how many Manuscripts to update.
   */
  limit?: number
}

/**
 * Manuscript updateManyAndReturn
 */
export type ManuscriptUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * The data used to update Manuscripts.
   */
  data: Prisma.XOR<Prisma.ManuscriptUpdateManyMutationInput, Prisma.ManuscriptUncheckedUpdateManyInput>
  /**
   * Filter which Manuscripts to update
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * Limit how many Manuscripts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Manuscript upsert
 */
export type ManuscriptUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * The filter to search for the Manuscript to update in case it exists.
   */
  where: Prisma.ManuscriptWhereUniqueInput
  /**
   * In case the Manuscript found by the `where` argument doesn't exist, create a new Manuscript with this data.
   */
  create: Prisma.XOR<Prisma.ManuscriptCreateInput, Prisma.ManuscriptUncheckedCreateInput>
  /**
   * In case the Manuscript was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ManuscriptUpdateInput, Prisma.ManuscriptUncheckedUpdateInput>
}

/**
 * Manuscript delete
 */
export type ManuscriptDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
  /**
   * Filter which Manuscript to delete.
   */
  where: Prisma.ManuscriptWhereUniqueInput
}

/**
 * Manuscript deleteMany
 */
export type ManuscriptDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Manuscripts to delete
   */
  where?: Prisma.ManuscriptWhereInput
  /**
   * Limit how many Manuscripts to delete.
   */
  limit?: number
}

/**
 * Manuscript without action
 */
export type ManuscriptDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manuscript
   */
  select?: Prisma.ManuscriptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manuscript
   */
  omit?: Prisma.ManuscriptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManuscriptInclude<ExtArgs> | null
}
