
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Paper` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Paper
 * 
 */
export type PaperModel = runtime.Types.Result.DefaultSelection<Prisma.$PaperPayload>

export type AggregatePaper = {
  _count: PaperCountAggregateOutputType | null
  _avg: PaperAvgAggregateOutputType | null
  _sum: PaperSumAggregateOutputType | null
  _min: PaperMinAggregateOutputType | null
  _max: PaperMaxAggregateOutputType | null
}

export type PaperAvgAggregateOutputType = {
  year: number | null
  impactFactor: number | null
}

export type PaperSumAggregateOutputType = {
  year: number | null
  impactFactor: number | null
}

export type PaperMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  doi: string | null
  pmid: string | null
  title: string | null
  journal: string | null
  year: number | null
  impactFactor: number | null
  abstract: string | null
  fullText: string | null
  source: string | null
  oaUrl: string | null
  createdAt: Date | null
}

export type PaperMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  doi: string | null
  pmid: string | null
  title: string | null
  journal: string | null
  year: number | null
  impactFactor: number | null
  abstract: string | null
  fullText: string | null
  source: string | null
  oaUrl: string | null
  createdAt: Date | null
}

export type PaperCountAggregateOutputType = {
  id: number
  projectId: number
  doi: number
  pmid: number
  title: number
  authors: number
  journal: number
  year: number
  impactFactor: number
  abstract: number
  fullText: number
  source: number
  oaUrl: number
  createdAt: number
  _all: number
}


export type PaperAvgAggregateInputType = {
  year?: true
  impactFactor?: true
}

export type PaperSumAggregateInputType = {
  year?: true
  impactFactor?: true
}

export type PaperMinAggregateInputType = {
  id?: true
  projectId?: true
  doi?: true
  pmid?: true
  title?: true
  journal?: true
  year?: true
  impactFactor?: true
  abstract?: true
  fullText?: true
  source?: true
  oaUrl?: true
  createdAt?: true
}

export type PaperMaxAggregateInputType = {
  id?: true
  projectId?: true
  doi?: true
  pmid?: true
  title?: true
  journal?: true
  year?: true
  impactFactor?: true
  abstract?: true
  fullText?: true
  source?: true
  oaUrl?: true
  createdAt?: true
}

export type PaperCountAggregateInputType = {
  id?: true
  projectId?: true
  doi?: true
  pmid?: true
  title?: true
  authors?: true
  journal?: true
  year?: true
  impactFactor?: true
  abstract?: true
  fullText?: true
  source?: true
  oaUrl?: true
  createdAt?: true
  _all?: true
}

export type PaperAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Paper to aggregate.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Papers
  **/
  _count?: true | PaperCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PaperAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PaperSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaperMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaperMaxAggregateInputType
}

export type GetPaperAggregateType<T extends PaperAggregateArgs> = {
      [P in keyof T & keyof AggregatePaper]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaper[P]>
    : Prisma.GetScalarType<T[P], AggregatePaper[P]>
}




export type PaperGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaperWhereInput
  orderBy?: Prisma.PaperOrderByWithAggregationInput | Prisma.PaperOrderByWithAggregationInput[]
  by: Prisma.PaperScalarFieldEnum[] | Prisma.PaperScalarFieldEnum
  having?: Prisma.PaperScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaperCountAggregateInputType | true
  _avg?: PaperAvgAggregateInputType
  _sum?: PaperSumAggregateInputType
  _min?: PaperMinAggregateInputType
  _max?: PaperMaxAggregateInputType
}

export type PaperGroupByOutputType = {
  id: string
  projectId: string
  doi: string | null
  pmid: string | null
  title: string
  authors: string[]
  journal: string | null
  year: number | null
  impactFactor: number | null
  abstract: string | null
  fullText: string | null
  source: string | null
  oaUrl: string | null
  createdAt: Date
  _count: PaperCountAggregateOutputType | null
  _avg: PaperAvgAggregateOutputType | null
  _sum: PaperSumAggregateOutputType | null
  _min: PaperMinAggregateOutputType | null
  _max: PaperMaxAggregateOutputType | null
}

export type GetPaperGroupByPayload<T extends PaperGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaperGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaperGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaperGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaperGroupByOutputType[P]>
      }
    >
  >



export type PaperWhereInput = {
  AND?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  OR?: Prisma.PaperWhereInput[]
  NOT?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  id?: Prisma.StringFilter<"Paper"> | string
  projectId?: Prisma.StringFilter<"Paper"> | string
  doi?: Prisma.StringNullableFilter<"Paper"> | string | null
  pmid?: Prisma.StringNullableFilter<"Paper"> | string | null
  title?: Prisma.StringFilter<"Paper"> | string
  authors?: Prisma.StringNullableListFilter<"Paper">
  journal?: Prisma.StringNullableFilter<"Paper"> | string | null
  year?: Prisma.IntNullableFilter<"Paper"> | number | null
  impactFactor?: Prisma.FloatNullableFilter<"Paper"> | number | null
  abstract?: Prisma.StringNullableFilter<"Paper"> | string | null
  fullText?: Prisma.StringNullableFilter<"Paper"> | string | null
  source?: Prisma.StringNullableFilter<"Paper"> | string | null
  oaUrl?: Prisma.StringNullableFilter<"Paper"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Paper"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  extractions?: Prisma.ExtractionListRelationFilter
}

export type PaperOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  doi?: Prisma.SortOrderInput | Prisma.SortOrder
  pmid?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  authors?: Prisma.SortOrder
  journal?: Prisma.SortOrderInput | Prisma.SortOrder
  year?: Prisma.SortOrderInput | Prisma.SortOrder
  impactFactor?: Prisma.SortOrderInput | Prisma.SortOrder
  abstract?: Prisma.SortOrderInput | Prisma.SortOrder
  fullText?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  oaUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  extractions?: Prisma.ExtractionOrderByRelationAggregateInput
}

export type PaperWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  doi?: string
  AND?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  OR?: Prisma.PaperWhereInput[]
  NOT?: Prisma.PaperWhereInput | Prisma.PaperWhereInput[]
  projectId?: Prisma.StringFilter<"Paper"> | string
  pmid?: Prisma.StringNullableFilter<"Paper"> | string | null
  title?: Prisma.StringFilter<"Paper"> | string
  authors?: Prisma.StringNullableListFilter<"Paper">
  journal?: Prisma.StringNullableFilter<"Paper"> | string | null
  year?: Prisma.IntNullableFilter<"Paper"> | number | null
  impactFactor?: Prisma.FloatNullableFilter<"Paper"> | number | null
  abstract?: Prisma.StringNullableFilter<"Paper"> | string | null
  fullText?: Prisma.StringNullableFilter<"Paper"> | string | null
  source?: Prisma.StringNullableFilter<"Paper"> | string | null
  oaUrl?: Prisma.StringNullableFilter<"Paper"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Paper"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  extractions?: Prisma.ExtractionListRelationFilter
}, "id" | "doi">

export type PaperOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  doi?: Prisma.SortOrderInput | Prisma.SortOrder
  pmid?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  authors?: Prisma.SortOrder
  journal?: Prisma.SortOrderInput | Prisma.SortOrder
  year?: Prisma.SortOrderInput | Prisma.SortOrder
  impactFactor?: Prisma.SortOrderInput | Prisma.SortOrder
  abstract?: Prisma.SortOrderInput | Prisma.SortOrder
  fullText?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  oaUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PaperCountOrderByAggregateInput
  _avg?: Prisma.PaperAvgOrderByAggregateInput
  _max?: Prisma.PaperMaxOrderByAggregateInput
  _min?: Prisma.PaperMinOrderByAggregateInput
  _sum?: Prisma.PaperSumOrderByAggregateInput
}

export type PaperScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaperScalarWhereWithAggregatesInput | Prisma.PaperScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaperScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaperScalarWhereWithAggregatesInput | Prisma.PaperScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  doi?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  pmid?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  title?: Prisma.StringWithAggregatesFilter<"Paper"> | string
  authors?: Prisma.StringNullableListFilter<"Paper">
  journal?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  year?: Prisma.IntNullableWithAggregatesFilter<"Paper"> | number | null
  impactFactor?: Prisma.FloatNullableWithAggregatesFilter<"Paper"> | number | null
  abstract?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  fullText?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  source?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  oaUrl?: Prisma.StringNullableWithAggregatesFilter<"Paper"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Paper"> | Date | string
}

export type PaperCreateInput = {
  id?: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutPapersInput
  extractions?: Prisma.ExtractionCreateNestedManyWithoutPaperInput
}

export type PaperUncheckedCreateInput = {
  id?: string
  projectId: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
  extractions?: Prisma.ExtractionUncheckedCreateNestedManyWithoutPaperInput
}

export type PaperUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutPapersNestedInput
  extractions?: Prisma.ExtractionUpdateManyWithoutPaperNestedInput
}

export type PaperUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extractions?: Prisma.ExtractionUncheckedUpdateManyWithoutPaperNestedInput
}

export type PaperCreateManyInput = {
  id?: string
  projectId: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
}

export type PaperUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaperUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaperListRelationFilter = {
  every?: Prisma.PaperWhereInput
  some?: Prisma.PaperWhereInput
  none?: Prisma.PaperWhereInput
}

export type PaperOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type PaperCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  doi?: Prisma.SortOrder
  pmid?: Prisma.SortOrder
  title?: Prisma.SortOrder
  authors?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  year?: Prisma.SortOrder
  impactFactor?: Prisma.SortOrder
  abstract?: Prisma.SortOrder
  fullText?: Prisma.SortOrder
  source?: Prisma.SortOrder
  oaUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PaperAvgOrderByAggregateInput = {
  year?: Prisma.SortOrder
  impactFactor?: Prisma.SortOrder
}

export type PaperMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  doi?: Prisma.SortOrder
  pmid?: Prisma.SortOrder
  title?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  year?: Prisma.SortOrder
  impactFactor?: Prisma.SortOrder
  abstract?: Prisma.SortOrder
  fullText?: Prisma.SortOrder
  source?: Prisma.SortOrder
  oaUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PaperMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  doi?: Prisma.SortOrder
  pmid?: Prisma.SortOrder
  title?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  year?: Prisma.SortOrder
  impactFactor?: Prisma.SortOrder
  abstract?: Prisma.SortOrder
  fullText?: Prisma.SortOrder
  source?: Prisma.SortOrder
  oaUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PaperSumOrderByAggregateInput = {
  year?: Prisma.SortOrder
  impactFactor?: Prisma.SortOrder
}

export type PaperScalarRelationFilter = {
  is?: Prisma.PaperWhereInput
  isNot?: Prisma.PaperWhereInput
}

export type PaperCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutProjectInput, Prisma.PaperUncheckedCreateWithoutProjectInput> | Prisma.PaperCreateWithoutProjectInput[] | Prisma.PaperUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutProjectInput | Prisma.PaperCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.PaperCreateManyProjectInputEnvelope
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
}

export type PaperUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutProjectInput, Prisma.PaperUncheckedCreateWithoutProjectInput> | Prisma.PaperCreateWithoutProjectInput[] | Prisma.PaperUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutProjectInput | Prisma.PaperCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.PaperCreateManyProjectInputEnvelope
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
}

export type PaperUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutProjectInput, Prisma.PaperUncheckedCreateWithoutProjectInput> | Prisma.PaperCreateWithoutProjectInput[] | Prisma.PaperUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutProjectInput | Prisma.PaperCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.PaperUpsertWithWhereUniqueWithoutProjectInput | Prisma.PaperUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.PaperCreateManyProjectInputEnvelope
  set?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  disconnect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  delete?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  update?: Prisma.PaperUpdateWithWhereUniqueWithoutProjectInput | Prisma.PaperUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.PaperUpdateManyWithWhereWithoutProjectInput | Prisma.PaperUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
}

export type PaperUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutProjectInput, Prisma.PaperUncheckedCreateWithoutProjectInput> | Prisma.PaperCreateWithoutProjectInput[] | Prisma.PaperUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutProjectInput | Prisma.PaperCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.PaperUpsertWithWhereUniqueWithoutProjectInput | Prisma.PaperUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.PaperCreateManyProjectInputEnvelope
  set?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  disconnect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  delete?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  connect?: Prisma.PaperWhereUniqueInput | Prisma.PaperWhereUniqueInput[]
  update?: Prisma.PaperUpdateWithWhereUniqueWithoutProjectInput | Prisma.PaperUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.PaperUpdateManyWithWhereWithoutProjectInput | Prisma.PaperUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
}

export type PaperCreateauthorsInput = {
  set: string[]
}

export type PaperUpdateauthorsInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PaperCreateNestedOneWithoutExtractionsInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutExtractionsInput, Prisma.PaperUncheckedCreateWithoutExtractionsInput>
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutExtractionsInput
  connect?: Prisma.PaperWhereUniqueInput
}

export type PaperUpdateOneRequiredWithoutExtractionsNestedInput = {
  create?: Prisma.XOR<Prisma.PaperCreateWithoutExtractionsInput, Prisma.PaperUncheckedCreateWithoutExtractionsInput>
  connectOrCreate?: Prisma.PaperCreateOrConnectWithoutExtractionsInput
  upsert?: Prisma.PaperUpsertWithoutExtractionsInput
  connect?: Prisma.PaperWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PaperUpdateToOneWithWhereWithoutExtractionsInput, Prisma.PaperUpdateWithoutExtractionsInput>, Prisma.PaperUncheckedUpdateWithoutExtractionsInput>
}

export type PaperCreateWithoutProjectInput = {
  id?: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
  extractions?: Prisma.ExtractionCreateNestedManyWithoutPaperInput
}

export type PaperUncheckedCreateWithoutProjectInput = {
  id?: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
  extractions?: Prisma.ExtractionUncheckedCreateNestedManyWithoutPaperInput
}

export type PaperCreateOrConnectWithoutProjectInput = {
  where: Prisma.PaperWhereUniqueInput
  create: Prisma.XOR<Prisma.PaperCreateWithoutProjectInput, Prisma.PaperUncheckedCreateWithoutProjectInput>
}

export type PaperCreateManyProjectInputEnvelope = {
  data: Prisma.PaperCreateManyProjectInput | Prisma.PaperCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type PaperUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.PaperWhereUniqueInput
  update: Prisma.XOR<Prisma.PaperUpdateWithoutProjectInput, Prisma.PaperUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.PaperCreateWithoutProjectInput, Prisma.PaperUncheckedCreateWithoutProjectInput>
}

export type PaperUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.PaperWhereUniqueInput
  data: Prisma.XOR<Prisma.PaperUpdateWithoutProjectInput, Prisma.PaperUncheckedUpdateWithoutProjectInput>
}

export type PaperUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.PaperScalarWhereInput
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyWithoutProjectInput>
}

export type PaperScalarWhereInput = {
  AND?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
  OR?: Prisma.PaperScalarWhereInput[]
  NOT?: Prisma.PaperScalarWhereInput | Prisma.PaperScalarWhereInput[]
  id?: Prisma.StringFilter<"Paper"> | string
  projectId?: Prisma.StringFilter<"Paper"> | string
  doi?: Prisma.StringNullableFilter<"Paper"> | string | null
  pmid?: Prisma.StringNullableFilter<"Paper"> | string | null
  title?: Prisma.StringFilter<"Paper"> | string
  authors?: Prisma.StringNullableListFilter<"Paper">
  journal?: Prisma.StringNullableFilter<"Paper"> | string | null
  year?: Prisma.IntNullableFilter<"Paper"> | number | null
  impactFactor?: Prisma.FloatNullableFilter<"Paper"> | number | null
  abstract?: Prisma.StringNullableFilter<"Paper"> | string | null
  fullText?: Prisma.StringNullableFilter<"Paper"> | string | null
  source?: Prisma.StringNullableFilter<"Paper"> | string | null
  oaUrl?: Prisma.StringNullableFilter<"Paper"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Paper"> | Date | string
}

export type PaperCreateWithoutExtractionsInput = {
  id?: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutPapersInput
}

export type PaperUncheckedCreateWithoutExtractionsInput = {
  id?: string
  projectId: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
}

export type PaperCreateOrConnectWithoutExtractionsInput = {
  where: Prisma.PaperWhereUniqueInput
  create: Prisma.XOR<Prisma.PaperCreateWithoutExtractionsInput, Prisma.PaperUncheckedCreateWithoutExtractionsInput>
}

export type PaperUpsertWithoutExtractionsInput = {
  update: Prisma.XOR<Prisma.PaperUpdateWithoutExtractionsInput, Prisma.PaperUncheckedUpdateWithoutExtractionsInput>
  create: Prisma.XOR<Prisma.PaperCreateWithoutExtractionsInput, Prisma.PaperUncheckedCreateWithoutExtractionsInput>
  where?: Prisma.PaperWhereInput
}

export type PaperUpdateToOneWithWhereWithoutExtractionsInput = {
  where?: Prisma.PaperWhereInput
  data: Prisma.XOR<Prisma.PaperUpdateWithoutExtractionsInput, Prisma.PaperUncheckedUpdateWithoutExtractionsInput>
}

export type PaperUpdateWithoutExtractionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutPapersNestedInput
}

export type PaperUncheckedUpdateWithoutExtractionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PaperCreateManyProjectInput = {
  id?: string
  doi?: string | null
  pmid?: string | null
  title: string
  authors?: Prisma.PaperCreateauthorsInput | string[]
  journal?: string | null
  year?: number | null
  impactFactor?: number | null
  abstract?: string | null
  fullText?: string | null
  source?: string | null
  oaUrl?: string | null
  createdAt?: Date | string
}

export type PaperUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extractions?: Prisma.ExtractionUpdateManyWithoutPaperNestedInput
}

export type PaperUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  extractions?: Prisma.ExtractionUncheckedUpdateManyWithoutPaperNestedInput
}

export type PaperUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  doi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pmid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  authors?: Prisma.PaperUpdateauthorsInput | string[]
  journal?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  impactFactor?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  abstract?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fullText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  oaUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PaperCountOutputType
 */

export type PaperCountOutputType = {
  extractions: number
}

export type PaperCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  extractions?: boolean | PaperCountOutputTypeCountExtractionsArgs
}

/**
 * PaperCountOutputType without action
 */
export type PaperCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaperCountOutputType
   */
  select?: Prisma.PaperCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PaperCountOutputType without action
 */
export type PaperCountOutputTypeCountExtractionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExtractionWhereInput
}


export type PaperSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  doi?: boolean
  pmid?: boolean
  title?: boolean
  authors?: boolean
  journal?: boolean
  year?: boolean
  impactFactor?: boolean
  abstract?: boolean
  fullText?: boolean
  source?: boolean
  oaUrl?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  extractions?: boolean | Prisma.Paper$extractionsArgs<ExtArgs>
  _count?: boolean | Prisma.PaperCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paper"]>

export type PaperSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  doi?: boolean
  pmid?: boolean
  title?: boolean
  authors?: boolean
  journal?: boolean
  year?: boolean
  impactFactor?: boolean
  abstract?: boolean
  fullText?: boolean
  source?: boolean
  oaUrl?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paper"]>

export type PaperSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  doi?: boolean
  pmid?: boolean
  title?: boolean
  authors?: boolean
  journal?: boolean
  year?: boolean
  impactFactor?: boolean
  abstract?: boolean
  fullText?: boolean
  source?: boolean
  oaUrl?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paper"]>

export type PaperSelectScalar = {
  id?: boolean
  projectId?: boolean
  doi?: boolean
  pmid?: boolean
  title?: boolean
  authors?: boolean
  journal?: boolean
  year?: boolean
  impactFactor?: boolean
  abstract?: boolean
  fullText?: boolean
  source?: boolean
  oaUrl?: boolean
  createdAt?: boolean
}

export type PaperOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "doi" | "pmid" | "title" | "authors" | "journal" | "year" | "impactFactor" | "abstract" | "fullText" | "source" | "oaUrl" | "createdAt", ExtArgs["result"]["paper"]>
export type PaperInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  extractions?: boolean | Prisma.Paper$extractionsArgs<ExtArgs>
  _count?: boolean | Prisma.PaperCountOutputTypeDefaultArgs<ExtArgs>
}
export type PaperIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type PaperIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $PaperPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Paper"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    extractions: Prisma.$ExtractionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    doi: string | null
    pmid: string | null
    title: string
    authors: string[]
    journal: string | null
    year: number | null
    impactFactor: number | null
    abstract: string | null
    fullText: string | null
    source: string | null
    oaUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["paper"]>
  composites: {}
}

export type PaperGetPayload<S extends boolean | null | undefined | PaperDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaperPayload, S>

export type PaperCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaperFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaperCountAggregateInputType | true
  }

export interface PaperDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Paper'], meta: { name: 'Paper' } }
  /**
   * Find zero or one Paper that matches the filter.
   * @param {PaperFindUniqueArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaperFindUniqueArgs>(args: Prisma.SelectSubset<T, PaperFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Paper that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaperFindUniqueOrThrowArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaperFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaperFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Paper that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperFindFirstArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaperFindFirstArgs>(args?: Prisma.SelectSubset<T, PaperFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Paper that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperFindFirstOrThrowArgs} args - Arguments to find a Paper
   * @example
   * // Get one Paper
   * const paper = await prisma.paper.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaperFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaperFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Papers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Papers
   * const papers = await prisma.paper.findMany()
   * 
   * // Get first 10 Papers
   * const papers = await prisma.paper.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paperWithIdOnly = await prisma.paper.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaperFindManyArgs>(args?: Prisma.SelectSubset<T, PaperFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Paper.
   * @param {PaperCreateArgs} args - Arguments to create a Paper.
   * @example
   * // Create one Paper
   * const Paper = await prisma.paper.create({
   *   data: {
   *     // ... data to create a Paper
   *   }
   * })
   * 
   */
  create<T extends PaperCreateArgs>(args: Prisma.SelectSubset<T, PaperCreateArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Papers.
   * @param {PaperCreateManyArgs} args - Arguments to create many Papers.
   * @example
   * // Create many Papers
   * const paper = await prisma.paper.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaperCreateManyArgs>(args?: Prisma.SelectSubset<T, PaperCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Papers and returns the data saved in the database.
   * @param {PaperCreateManyAndReturnArgs} args - Arguments to create many Papers.
   * @example
   * // Create many Papers
   * const paper = await prisma.paper.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Papers and only return the `id`
   * const paperWithIdOnly = await prisma.paper.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PaperCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PaperCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Paper.
   * @param {PaperDeleteArgs} args - Arguments to delete one Paper.
   * @example
   * // Delete one Paper
   * const Paper = await prisma.paper.delete({
   *   where: {
   *     // ... filter to delete one Paper
   *   }
   * })
   * 
   */
  delete<T extends PaperDeleteArgs>(args: Prisma.SelectSubset<T, PaperDeleteArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Paper.
   * @param {PaperUpdateArgs} args - Arguments to update one Paper.
   * @example
   * // Update one Paper
   * const paper = await prisma.paper.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaperUpdateArgs>(args: Prisma.SelectSubset<T, PaperUpdateArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Papers.
   * @param {PaperDeleteManyArgs} args - Arguments to filter Papers to delete.
   * @example
   * // Delete a few Papers
   * const { count } = await prisma.paper.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaperDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaperDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Papers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Papers
   * const paper = await prisma.paper.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaperUpdateManyArgs>(args: Prisma.SelectSubset<T, PaperUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Papers and returns the data updated in the database.
   * @param {PaperUpdateManyAndReturnArgs} args - Arguments to update many Papers.
   * @example
   * // Update many Papers
   * const paper = await prisma.paper.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Papers and only return the `id`
   * const paperWithIdOnly = await prisma.paper.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PaperUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PaperUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Paper.
   * @param {PaperUpsertArgs} args - Arguments to update or create a Paper.
   * @example
   * // Update or create a Paper
   * const paper = await prisma.paper.upsert({
   *   create: {
   *     // ... data to create a Paper
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Paper we want to update
   *   }
   * })
   */
  upsert<T extends PaperUpsertArgs>(args: Prisma.SelectSubset<T, PaperUpsertArgs<ExtArgs>>): Prisma.Prisma__PaperClient<runtime.Types.Result.GetResult<Prisma.$PaperPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Papers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperCountArgs} args - Arguments to filter Papers to count.
   * @example
   * // Count the number of Papers
   * const count = await prisma.paper.count({
   *   where: {
   *     // ... the filter for the Papers we want to count
   *   }
   * })
  **/
  count<T extends PaperCountArgs>(
    args?: Prisma.Subset<T, PaperCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaperCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Paper.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaperAggregateArgs>(args: Prisma.Subset<T, PaperAggregateArgs>): Prisma.PrismaPromise<GetPaperAggregateType<T>>

  /**
   * Group by Paper.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaperGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaperGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaperGroupByArgs['orderBy'] }
      : { orderBy?: PaperGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaperGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaperGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Paper model
 */
readonly fields: PaperFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Paper.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaperClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  extractions<T extends Prisma.Paper$extractionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Paper$extractionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExtractionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Paper model
 */
export interface PaperFieldRefs {
  readonly id: Prisma.FieldRef<"Paper", 'String'>
  readonly projectId: Prisma.FieldRef<"Paper", 'String'>
  readonly doi: Prisma.FieldRef<"Paper", 'String'>
  readonly pmid: Prisma.FieldRef<"Paper", 'String'>
  readonly title: Prisma.FieldRef<"Paper", 'String'>
  readonly authors: Prisma.FieldRef<"Paper", 'String[]'>
  readonly journal: Prisma.FieldRef<"Paper", 'String'>
  readonly year: Prisma.FieldRef<"Paper", 'Int'>
  readonly impactFactor: Prisma.FieldRef<"Paper", 'Float'>
  readonly abstract: Prisma.FieldRef<"Paper", 'String'>
  readonly fullText: Prisma.FieldRef<"Paper", 'String'>
  readonly source: Prisma.FieldRef<"Paper", 'String'>
  readonly oaUrl: Prisma.FieldRef<"Paper", 'String'>
  readonly createdAt: Prisma.FieldRef<"Paper", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Paper findUnique
 */
export type PaperFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper findUniqueOrThrow
 */
export type PaperFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper findFirst
 */
export type PaperFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Papers.
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Papers.
   */
  distinct?: Prisma.PaperScalarFieldEnum | Prisma.PaperScalarFieldEnum[]
}

/**
 * Paper findFirstOrThrow
 */
export type PaperFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Paper to fetch.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Papers.
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Papers.
   */
  distinct?: Prisma.PaperScalarFieldEnum | Prisma.PaperScalarFieldEnum[]
}

/**
 * Paper findMany
 */
export type PaperFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter, which Papers to fetch.
   */
  where?: Prisma.PaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Papers to fetch.
   */
  orderBy?: Prisma.PaperOrderByWithRelationInput | Prisma.PaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Papers.
   */
  cursor?: Prisma.PaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Papers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Papers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Papers.
   */
  distinct?: Prisma.PaperScalarFieldEnum | Prisma.PaperScalarFieldEnum[]
}

/**
 * Paper create
 */
export type PaperCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * The data needed to create a Paper.
   */
  data: Prisma.XOR<Prisma.PaperCreateInput, Prisma.PaperUncheckedCreateInput>
}

/**
 * Paper createMany
 */
export type PaperCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Papers.
   */
  data: Prisma.PaperCreateManyInput | Prisma.PaperCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Paper createManyAndReturn
 */
export type PaperCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * The data used to create many Papers.
   */
  data: Prisma.PaperCreateManyInput | Prisma.PaperCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Paper update
 */
export type PaperUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * The data needed to update a Paper.
   */
  data: Prisma.XOR<Prisma.PaperUpdateInput, Prisma.PaperUncheckedUpdateInput>
  /**
   * Choose, which Paper to update.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper updateMany
 */
export type PaperUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Papers.
   */
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyInput>
  /**
   * Filter which Papers to update
   */
  where?: Prisma.PaperWhereInput
  /**
   * Limit how many Papers to update.
   */
  limit?: number
}

/**
 * Paper updateManyAndReturn
 */
export type PaperUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * The data used to update Papers.
   */
  data: Prisma.XOR<Prisma.PaperUpdateManyMutationInput, Prisma.PaperUncheckedUpdateManyInput>
  /**
   * Filter which Papers to update
   */
  where?: Prisma.PaperWhereInput
  /**
   * Limit how many Papers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Paper upsert
 */
export type PaperUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * The filter to search for the Paper to update in case it exists.
   */
  where: Prisma.PaperWhereUniqueInput
  /**
   * In case the Paper found by the `where` argument doesn't exist, create a new Paper with this data.
   */
  create: Prisma.XOR<Prisma.PaperCreateInput, Prisma.PaperUncheckedCreateInput>
  /**
   * In case the Paper was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaperUpdateInput, Prisma.PaperUncheckedUpdateInput>
}

/**
 * Paper delete
 */
export type PaperDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
  /**
   * Filter which Paper to delete.
   */
  where: Prisma.PaperWhereUniqueInput
}

/**
 * Paper deleteMany
 */
export type PaperDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Papers to delete
   */
  where?: Prisma.PaperWhereInput
  /**
   * Limit how many Papers to delete.
   */
  limit?: number
}

/**
 * Paper.extractions
 */
export type Paper$extractionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Extraction
   */
  select?: Prisma.ExtractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Extraction
   */
  omit?: Prisma.ExtractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExtractionInclude<ExtArgs> | null
  where?: Prisma.ExtractionWhereInput
  orderBy?: Prisma.ExtractionOrderByWithRelationInput | Prisma.ExtractionOrderByWithRelationInput[]
  cursor?: Prisma.ExtractionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExtractionScalarFieldEnum | Prisma.ExtractionScalarFieldEnum[]
}

/**
 * Paper without action
 */
export type PaperDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Paper
   */
  select?: Prisma.PaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Paper
   */
  omit?: Prisma.PaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaperInclude<ExtArgs> | null
}
