
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TimelineEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TimelineEvent
 * 
 */
export type TimelineEventModel = runtime.Types.Result.DefaultSelection<Prisma.$TimelineEventPayload>

export type AggregateTimelineEvent = {
  _count: TimelineEventCountAggregateOutputType | null
  _avg: TimelineEventAvgAggregateOutputType | null
  _sum: TimelineEventSumAggregateOutputType | null
  _min: TimelineEventMinAggregateOutputType | null
  _max: TimelineEventMaxAggregateOutputType | null
}

export type TimelineEventAvgAggregateOutputType = {
  sortOrder: number | null
  weekNumber: number | null
}

export type TimelineEventSumAggregateOutputType = {
  sortOrder: number | null
  weekNumber: number | null
}

export type TimelineEventMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  type: string | null
  title: string | null
  sortOrder: number | null
  weekNumber: number | null
  createdAt: Date | null
}

export type TimelineEventMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  type: string | null
  title: string | null
  sortOrder: number | null
  weekNumber: number | null
  createdAt: Date | null
}

export type TimelineEventCountAggregateOutputType = {
  id: number
  projectId: number
  type: number
  title: number
  content: number
  metadata: number
  sortOrder: number
  weekNumber: number
  createdAt: number
  _all: number
}


export type TimelineEventAvgAggregateInputType = {
  sortOrder?: true
  weekNumber?: true
}

export type TimelineEventSumAggregateInputType = {
  sortOrder?: true
  weekNumber?: true
}

export type TimelineEventMinAggregateInputType = {
  id?: true
  projectId?: true
  type?: true
  title?: true
  sortOrder?: true
  weekNumber?: true
  createdAt?: true
}

export type TimelineEventMaxAggregateInputType = {
  id?: true
  projectId?: true
  type?: true
  title?: true
  sortOrder?: true
  weekNumber?: true
  createdAt?: true
}

export type TimelineEventCountAggregateInputType = {
  id?: true
  projectId?: true
  type?: true
  title?: true
  content?: true
  metadata?: true
  sortOrder?: true
  weekNumber?: true
  createdAt?: true
  _all?: true
}

export type TimelineEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimelineEvent to aggregate.
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimelineEvents to fetch.
   */
  orderBy?: Prisma.TimelineEventOrderByWithRelationInput | Prisma.TimelineEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TimelineEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimelineEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimelineEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TimelineEvents
  **/
  _count?: true | TimelineEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TimelineEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TimelineEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimelineEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimelineEventMaxAggregateInputType
}

export type GetTimelineEventAggregateType<T extends TimelineEventAggregateArgs> = {
      [P in keyof T & keyof AggregateTimelineEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTimelineEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateTimelineEvent[P]>
}




export type TimelineEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimelineEventWhereInput
  orderBy?: Prisma.TimelineEventOrderByWithAggregationInput | Prisma.TimelineEventOrderByWithAggregationInput[]
  by: Prisma.TimelineEventScalarFieldEnum[] | Prisma.TimelineEventScalarFieldEnum
  having?: Prisma.TimelineEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimelineEventCountAggregateInputType | true
  _avg?: TimelineEventAvgAggregateInputType
  _sum?: TimelineEventSumAggregateInputType
  _min?: TimelineEventMinAggregateInputType
  _max?: TimelineEventMaxAggregateInputType
}

export type TimelineEventGroupByOutputType = {
  id: string
  projectId: string
  type: string
  title: string
  content: runtime.JsonValue
  metadata: runtime.JsonValue | null
  sortOrder: number
  weekNumber: number | null
  createdAt: Date
  _count: TimelineEventCountAggregateOutputType | null
  _avg: TimelineEventAvgAggregateOutputType | null
  _sum: TimelineEventSumAggregateOutputType | null
  _min: TimelineEventMinAggregateOutputType | null
  _max: TimelineEventMaxAggregateOutputType | null
}

export type GetTimelineEventGroupByPayload<T extends TimelineEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimelineEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimelineEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimelineEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimelineEventGroupByOutputType[P]>
      }
    >
  >



export type TimelineEventWhereInput = {
  AND?: Prisma.TimelineEventWhereInput | Prisma.TimelineEventWhereInput[]
  OR?: Prisma.TimelineEventWhereInput[]
  NOT?: Prisma.TimelineEventWhereInput | Prisma.TimelineEventWhereInput[]
  id?: Prisma.StringFilter<"TimelineEvent"> | string
  projectId?: Prisma.StringFilter<"TimelineEvent"> | string
  type?: Prisma.StringFilter<"TimelineEvent"> | string
  title?: Prisma.StringFilter<"TimelineEvent"> | string
  content?: Prisma.JsonFilter<"TimelineEvent">
  metadata?: Prisma.JsonNullableFilter<"TimelineEvent">
  sortOrder?: Prisma.IntFilter<"TimelineEvent"> | number
  weekNumber?: Prisma.IntNullableFilter<"TimelineEvent"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TimelineEvent"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type TimelineEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type TimelineEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TimelineEventWhereInput | Prisma.TimelineEventWhereInput[]
  OR?: Prisma.TimelineEventWhereInput[]
  NOT?: Prisma.TimelineEventWhereInput | Prisma.TimelineEventWhereInput[]
  projectId?: Prisma.StringFilter<"TimelineEvent"> | string
  type?: Prisma.StringFilter<"TimelineEvent"> | string
  title?: Prisma.StringFilter<"TimelineEvent"> | string
  content?: Prisma.JsonFilter<"TimelineEvent">
  metadata?: Prisma.JsonNullableFilter<"TimelineEvent">
  sortOrder?: Prisma.IntFilter<"TimelineEvent"> | number
  weekNumber?: Prisma.IntNullableFilter<"TimelineEvent"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TimelineEvent"> | Date | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id">

export type TimelineEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TimelineEventCountOrderByAggregateInput
  _avg?: Prisma.TimelineEventAvgOrderByAggregateInput
  _max?: Prisma.TimelineEventMaxOrderByAggregateInput
  _min?: Prisma.TimelineEventMinOrderByAggregateInput
  _sum?: Prisma.TimelineEventSumOrderByAggregateInput
}

export type TimelineEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.TimelineEventScalarWhereWithAggregatesInput | Prisma.TimelineEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.TimelineEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TimelineEventScalarWhereWithAggregatesInput | Prisma.TimelineEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TimelineEvent"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"TimelineEvent"> | string
  type?: Prisma.StringWithAggregatesFilter<"TimelineEvent"> | string
  title?: Prisma.StringWithAggregatesFilter<"TimelineEvent"> | string
  content?: Prisma.JsonWithAggregatesFilter<"TimelineEvent">
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"TimelineEvent">
  sortOrder?: Prisma.IntWithAggregatesFilter<"TimelineEvent"> | number
  weekNumber?: Prisma.IntNullableWithAggregatesFilter<"TimelineEvent"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TimelineEvent"> | Date | string
}

export type TimelineEventCreateInput = {
  id?: string
  type: string
  title: string
  content: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: number
  weekNumber?: number | null
  createdAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutTimelineInput
}

export type TimelineEventUncheckedCreateInput = {
  id?: string
  projectId: string
  type: string
  title: string
  content: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: number
  weekNumber?: number | null
  createdAt?: Date | string
}

export type TimelineEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutTimelineNestedInput
}

export type TimelineEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimelineEventCreateManyInput = {
  id?: string
  projectId: string
  type: string
  title: string
  content: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: number
  weekNumber?: number | null
  createdAt?: Date | string
}

export type TimelineEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimelineEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimelineEventListRelationFilter = {
  every?: Prisma.TimelineEventWhereInput
  some?: Prisma.TimelineEventWhereInput
  none?: Prisma.TimelineEventWhereInput
}

export type TimelineEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TimelineEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TimelineEventAvgOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
}

export type TimelineEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TimelineEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TimelineEventSumOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
}

export type TimelineEventCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.TimelineEventCreateWithoutProjectInput, Prisma.TimelineEventUncheckedCreateWithoutProjectInput> | Prisma.TimelineEventCreateWithoutProjectInput[] | Prisma.TimelineEventUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.TimelineEventCreateOrConnectWithoutProjectInput | Prisma.TimelineEventCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.TimelineEventCreateManyProjectInputEnvelope
  connect?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
}

export type TimelineEventUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.TimelineEventCreateWithoutProjectInput, Prisma.TimelineEventUncheckedCreateWithoutProjectInput> | Prisma.TimelineEventCreateWithoutProjectInput[] | Prisma.TimelineEventUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.TimelineEventCreateOrConnectWithoutProjectInput | Prisma.TimelineEventCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.TimelineEventCreateManyProjectInputEnvelope
  connect?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
}

export type TimelineEventUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.TimelineEventCreateWithoutProjectInput, Prisma.TimelineEventUncheckedCreateWithoutProjectInput> | Prisma.TimelineEventCreateWithoutProjectInput[] | Prisma.TimelineEventUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.TimelineEventCreateOrConnectWithoutProjectInput | Prisma.TimelineEventCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.TimelineEventUpsertWithWhereUniqueWithoutProjectInput | Prisma.TimelineEventUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.TimelineEventCreateManyProjectInputEnvelope
  set?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  disconnect?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  delete?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  connect?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  update?: Prisma.TimelineEventUpdateWithWhereUniqueWithoutProjectInput | Prisma.TimelineEventUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.TimelineEventUpdateManyWithWhereWithoutProjectInput | Prisma.TimelineEventUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.TimelineEventScalarWhereInput | Prisma.TimelineEventScalarWhereInput[]
}

export type TimelineEventUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.TimelineEventCreateWithoutProjectInput, Prisma.TimelineEventUncheckedCreateWithoutProjectInput> | Prisma.TimelineEventCreateWithoutProjectInput[] | Prisma.TimelineEventUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.TimelineEventCreateOrConnectWithoutProjectInput | Prisma.TimelineEventCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.TimelineEventUpsertWithWhereUniqueWithoutProjectInput | Prisma.TimelineEventUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.TimelineEventCreateManyProjectInputEnvelope
  set?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  disconnect?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  delete?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  connect?: Prisma.TimelineEventWhereUniqueInput | Prisma.TimelineEventWhereUniqueInput[]
  update?: Prisma.TimelineEventUpdateWithWhereUniqueWithoutProjectInput | Prisma.TimelineEventUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.TimelineEventUpdateManyWithWhereWithoutProjectInput | Prisma.TimelineEventUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.TimelineEventScalarWhereInput | Prisma.TimelineEventScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TimelineEventCreateWithoutProjectInput = {
  id?: string
  type: string
  title: string
  content: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: number
  weekNumber?: number | null
  createdAt?: Date | string
}

export type TimelineEventUncheckedCreateWithoutProjectInput = {
  id?: string
  type: string
  title: string
  content: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: number
  weekNumber?: number | null
  createdAt?: Date | string
}

export type TimelineEventCreateOrConnectWithoutProjectInput = {
  where: Prisma.TimelineEventWhereUniqueInput
  create: Prisma.XOR<Prisma.TimelineEventCreateWithoutProjectInput, Prisma.TimelineEventUncheckedCreateWithoutProjectInput>
}

export type TimelineEventCreateManyProjectInputEnvelope = {
  data: Prisma.TimelineEventCreateManyProjectInput | Prisma.TimelineEventCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type TimelineEventUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.TimelineEventWhereUniqueInput
  update: Prisma.XOR<Prisma.TimelineEventUpdateWithoutProjectInput, Prisma.TimelineEventUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.TimelineEventCreateWithoutProjectInput, Prisma.TimelineEventUncheckedCreateWithoutProjectInput>
}

export type TimelineEventUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.TimelineEventWhereUniqueInput
  data: Prisma.XOR<Prisma.TimelineEventUpdateWithoutProjectInput, Prisma.TimelineEventUncheckedUpdateWithoutProjectInput>
}

export type TimelineEventUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.TimelineEventScalarWhereInput
  data: Prisma.XOR<Prisma.TimelineEventUpdateManyMutationInput, Prisma.TimelineEventUncheckedUpdateManyWithoutProjectInput>
}

export type TimelineEventScalarWhereInput = {
  AND?: Prisma.TimelineEventScalarWhereInput | Prisma.TimelineEventScalarWhereInput[]
  OR?: Prisma.TimelineEventScalarWhereInput[]
  NOT?: Prisma.TimelineEventScalarWhereInput | Prisma.TimelineEventScalarWhereInput[]
  id?: Prisma.StringFilter<"TimelineEvent"> | string
  projectId?: Prisma.StringFilter<"TimelineEvent"> | string
  type?: Prisma.StringFilter<"TimelineEvent"> | string
  title?: Prisma.StringFilter<"TimelineEvent"> | string
  content?: Prisma.JsonFilter<"TimelineEvent">
  metadata?: Prisma.JsonNullableFilter<"TimelineEvent">
  sortOrder?: Prisma.IntFilter<"TimelineEvent"> | number
  weekNumber?: Prisma.IntNullableFilter<"TimelineEvent"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TimelineEvent"> | Date | string
}

export type TimelineEventCreateManyProjectInput = {
  id?: string
  type: string
  title: string
  content: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: number
  weekNumber?: number | null
  createdAt?: Date | string
}

export type TimelineEventUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimelineEventUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimelineEventUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TimelineEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  type?: boolean
  title?: boolean
  content?: boolean
  metadata?: boolean
  sortOrder?: boolean
  weekNumber?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timelineEvent"]>

export type TimelineEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  type?: boolean
  title?: boolean
  content?: boolean
  metadata?: boolean
  sortOrder?: boolean
  weekNumber?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timelineEvent"]>

export type TimelineEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  type?: boolean
  title?: boolean
  content?: boolean
  metadata?: boolean
  sortOrder?: boolean
  weekNumber?: boolean
  createdAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["timelineEvent"]>

export type TimelineEventSelectScalar = {
  id?: boolean
  projectId?: boolean
  type?: boolean
  title?: boolean
  content?: boolean
  metadata?: boolean
  sortOrder?: boolean
  weekNumber?: boolean
  createdAt?: boolean
}

export type TimelineEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "type" | "title" | "content" | "metadata" | "sortOrder" | "weekNumber" | "createdAt", ExtArgs["result"]["timelineEvent"]>
export type TimelineEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type TimelineEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type TimelineEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $TimelineEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TimelineEvent"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    type: string
    title: string
    content: runtime.JsonValue
    metadata: runtime.JsonValue | null
    sortOrder: number
    weekNumber: number | null
    createdAt: Date
  }, ExtArgs["result"]["timelineEvent"]>
  composites: {}
}

export type TimelineEventGetPayload<S extends boolean | null | undefined | TimelineEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload, S>

export type TimelineEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TimelineEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TimelineEventCountAggregateInputType | true
  }

export interface TimelineEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TimelineEvent'], meta: { name: 'TimelineEvent' } }
  /**
   * Find zero or one TimelineEvent that matches the filter.
   * @param {TimelineEventFindUniqueArgs} args - Arguments to find a TimelineEvent
   * @example
   * // Get one TimelineEvent
   * const timelineEvent = await prisma.timelineEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TimelineEventFindUniqueArgs>(args: Prisma.SelectSubset<T, TimelineEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TimelineEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TimelineEventFindUniqueOrThrowArgs} args - Arguments to find a TimelineEvent
   * @example
   * // Get one TimelineEvent
   * const timelineEvent = await prisma.timelineEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TimelineEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TimelineEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimelineEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventFindFirstArgs} args - Arguments to find a TimelineEvent
   * @example
   * // Get one TimelineEvent
   * const timelineEvent = await prisma.timelineEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TimelineEventFindFirstArgs>(args?: Prisma.SelectSubset<T, TimelineEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimelineEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventFindFirstOrThrowArgs} args - Arguments to find a TimelineEvent
   * @example
   * // Get one TimelineEvent
   * const timelineEvent = await prisma.timelineEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TimelineEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TimelineEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TimelineEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TimelineEvents
   * const timelineEvents = await prisma.timelineEvent.findMany()
   * 
   * // Get first 10 TimelineEvents
   * const timelineEvents = await prisma.timelineEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const timelineEventWithIdOnly = await prisma.timelineEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TimelineEventFindManyArgs>(args?: Prisma.SelectSubset<T, TimelineEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TimelineEvent.
   * @param {TimelineEventCreateArgs} args - Arguments to create a TimelineEvent.
   * @example
   * // Create one TimelineEvent
   * const TimelineEvent = await prisma.timelineEvent.create({
   *   data: {
   *     // ... data to create a TimelineEvent
   *   }
   * })
   * 
   */
  create<T extends TimelineEventCreateArgs>(args: Prisma.SelectSubset<T, TimelineEventCreateArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TimelineEvents.
   * @param {TimelineEventCreateManyArgs} args - Arguments to create many TimelineEvents.
   * @example
   * // Create many TimelineEvents
   * const timelineEvent = await prisma.timelineEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TimelineEventCreateManyArgs>(args?: Prisma.SelectSubset<T, TimelineEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TimelineEvents and returns the data saved in the database.
   * @param {TimelineEventCreateManyAndReturnArgs} args - Arguments to create many TimelineEvents.
   * @example
   * // Create many TimelineEvents
   * const timelineEvent = await prisma.timelineEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TimelineEvents and only return the `id`
   * const timelineEventWithIdOnly = await prisma.timelineEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TimelineEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TimelineEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TimelineEvent.
   * @param {TimelineEventDeleteArgs} args - Arguments to delete one TimelineEvent.
   * @example
   * // Delete one TimelineEvent
   * const TimelineEvent = await prisma.timelineEvent.delete({
   *   where: {
   *     // ... filter to delete one TimelineEvent
   *   }
   * })
   * 
   */
  delete<T extends TimelineEventDeleteArgs>(args: Prisma.SelectSubset<T, TimelineEventDeleteArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TimelineEvent.
   * @param {TimelineEventUpdateArgs} args - Arguments to update one TimelineEvent.
   * @example
   * // Update one TimelineEvent
   * const timelineEvent = await prisma.timelineEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TimelineEventUpdateArgs>(args: Prisma.SelectSubset<T, TimelineEventUpdateArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TimelineEvents.
   * @param {TimelineEventDeleteManyArgs} args - Arguments to filter TimelineEvents to delete.
   * @example
   * // Delete a few TimelineEvents
   * const { count } = await prisma.timelineEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TimelineEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, TimelineEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimelineEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TimelineEvents
   * const timelineEvent = await prisma.timelineEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TimelineEventUpdateManyArgs>(args: Prisma.SelectSubset<T, TimelineEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimelineEvents and returns the data updated in the database.
   * @param {TimelineEventUpdateManyAndReturnArgs} args - Arguments to update many TimelineEvents.
   * @example
   * // Update many TimelineEvents
   * const timelineEvent = await prisma.timelineEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TimelineEvents and only return the `id`
   * const timelineEventWithIdOnly = await prisma.timelineEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TimelineEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TimelineEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TimelineEvent.
   * @param {TimelineEventUpsertArgs} args - Arguments to update or create a TimelineEvent.
   * @example
   * // Update or create a TimelineEvent
   * const timelineEvent = await prisma.timelineEvent.upsert({
   *   create: {
   *     // ... data to create a TimelineEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TimelineEvent we want to update
   *   }
   * })
   */
  upsert<T extends TimelineEventUpsertArgs>(args: Prisma.SelectSubset<T, TimelineEventUpsertArgs<ExtArgs>>): Prisma.Prisma__TimelineEventClient<runtime.Types.Result.GetResult<Prisma.$TimelineEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TimelineEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventCountArgs} args - Arguments to filter TimelineEvents to count.
   * @example
   * // Count the number of TimelineEvents
   * const count = await prisma.timelineEvent.count({
   *   where: {
   *     // ... the filter for the TimelineEvents we want to count
   *   }
   * })
  **/
  count<T extends TimelineEventCountArgs>(
    args?: Prisma.Subset<T, TimelineEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimelineEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TimelineEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimelineEventAggregateArgs>(args: Prisma.Subset<T, TimelineEventAggregateArgs>): Prisma.PrismaPromise<GetTimelineEventAggregateType<T>>

  /**
   * Group by TimelineEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimelineEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TimelineEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TimelineEventGroupByArgs['orderBy'] }
      : { orderBy?: TimelineEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TimelineEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimelineEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TimelineEvent model
 */
readonly fields: TimelineEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TimelineEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TimelineEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TimelineEvent model
 */
export interface TimelineEventFieldRefs {
  readonly id: Prisma.FieldRef<"TimelineEvent", 'String'>
  readonly projectId: Prisma.FieldRef<"TimelineEvent", 'String'>
  readonly type: Prisma.FieldRef<"TimelineEvent", 'String'>
  readonly title: Prisma.FieldRef<"TimelineEvent", 'String'>
  readonly content: Prisma.FieldRef<"TimelineEvent", 'Json'>
  readonly metadata: Prisma.FieldRef<"TimelineEvent", 'Json'>
  readonly sortOrder: Prisma.FieldRef<"TimelineEvent", 'Int'>
  readonly weekNumber: Prisma.FieldRef<"TimelineEvent", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TimelineEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TimelineEvent findUnique
 */
export type TimelineEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * Filter, which TimelineEvent to fetch.
   */
  where: Prisma.TimelineEventWhereUniqueInput
}

/**
 * TimelineEvent findUniqueOrThrow
 */
export type TimelineEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * Filter, which TimelineEvent to fetch.
   */
  where: Prisma.TimelineEventWhereUniqueInput
}

/**
 * TimelineEvent findFirst
 */
export type TimelineEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * Filter, which TimelineEvent to fetch.
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimelineEvents to fetch.
   */
  orderBy?: Prisma.TimelineEventOrderByWithRelationInput | Prisma.TimelineEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimelineEvents.
   */
  cursor?: Prisma.TimelineEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimelineEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimelineEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimelineEvents.
   */
  distinct?: Prisma.TimelineEventScalarFieldEnum | Prisma.TimelineEventScalarFieldEnum[]
}

/**
 * TimelineEvent findFirstOrThrow
 */
export type TimelineEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * Filter, which TimelineEvent to fetch.
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimelineEvents to fetch.
   */
  orderBy?: Prisma.TimelineEventOrderByWithRelationInput | Prisma.TimelineEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimelineEvents.
   */
  cursor?: Prisma.TimelineEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimelineEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimelineEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimelineEvents.
   */
  distinct?: Prisma.TimelineEventScalarFieldEnum | Prisma.TimelineEventScalarFieldEnum[]
}

/**
 * TimelineEvent findMany
 */
export type TimelineEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * Filter, which TimelineEvents to fetch.
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimelineEvents to fetch.
   */
  orderBy?: Prisma.TimelineEventOrderByWithRelationInput | Prisma.TimelineEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TimelineEvents.
   */
  cursor?: Prisma.TimelineEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimelineEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimelineEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimelineEvents.
   */
  distinct?: Prisma.TimelineEventScalarFieldEnum | Prisma.TimelineEventScalarFieldEnum[]
}

/**
 * TimelineEvent create
 */
export type TimelineEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * The data needed to create a TimelineEvent.
   */
  data: Prisma.XOR<Prisma.TimelineEventCreateInput, Prisma.TimelineEventUncheckedCreateInput>
}

/**
 * TimelineEvent createMany
 */
export type TimelineEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TimelineEvents.
   */
  data: Prisma.TimelineEventCreateManyInput | Prisma.TimelineEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TimelineEvent createManyAndReturn
 */
export type TimelineEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * The data used to create many TimelineEvents.
   */
  data: Prisma.TimelineEventCreateManyInput | Prisma.TimelineEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TimelineEvent update
 */
export type TimelineEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * The data needed to update a TimelineEvent.
   */
  data: Prisma.XOR<Prisma.TimelineEventUpdateInput, Prisma.TimelineEventUncheckedUpdateInput>
  /**
   * Choose, which TimelineEvent to update.
   */
  where: Prisma.TimelineEventWhereUniqueInput
}

/**
 * TimelineEvent updateMany
 */
export type TimelineEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TimelineEvents.
   */
  data: Prisma.XOR<Prisma.TimelineEventUpdateManyMutationInput, Prisma.TimelineEventUncheckedUpdateManyInput>
  /**
   * Filter which TimelineEvents to update
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * Limit how many TimelineEvents to update.
   */
  limit?: number
}

/**
 * TimelineEvent updateManyAndReturn
 */
export type TimelineEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * The data used to update TimelineEvents.
   */
  data: Prisma.XOR<Prisma.TimelineEventUpdateManyMutationInput, Prisma.TimelineEventUncheckedUpdateManyInput>
  /**
   * Filter which TimelineEvents to update
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * Limit how many TimelineEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TimelineEvent upsert
 */
export type TimelineEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * The filter to search for the TimelineEvent to update in case it exists.
   */
  where: Prisma.TimelineEventWhereUniqueInput
  /**
   * In case the TimelineEvent found by the `where` argument doesn't exist, create a new TimelineEvent with this data.
   */
  create: Prisma.XOR<Prisma.TimelineEventCreateInput, Prisma.TimelineEventUncheckedCreateInput>
  /**
   * In case the TimelineEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TimelineEventUpdateInput, Prisma.TimelineEventUncheckedUpdateInput>
}

/**
 * TimelineEvent delete
 */
export type TimelineEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
  /**
   * Filter which TimelineEvent to delete.
   */
  where: Prisma.TimelineEventWhereUniqueInput
}

/**
 * TimelineEvent deleteMany
 */
export type TimelineEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimelineEvents to delete
   */
  where?: Prisma.TimelineEventWhereInput
  /**
   * Limit how many TimelineEvents to delete.
   */
  limit?: number
}

/**
 * TimelineEvent without action
 */
export type TimelineEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimelineEvent
   */
  select?: Prisma.TimelineEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimelineEvent
   */
  omit?: Prisma.TimelineEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimelineEventInclude<ExtArgs> | null
}
