
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Project: 'Project',
  Paper: 'Paper',
  Extraction: 'Extraction',
  Hypothesis: 'Hypothesis',
  Experiment: 'Experiment',
  ExperimentData: 'ExperimentData',
  TimelineEvent: 'TimelineEvent',
  Manuscript: 'Manuscript'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  avatar: 'avatar',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const PaperScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  doi: 'doi',
  pmid: 'pmid',
  title: 'title',
  authors: 'authors',
  journal: 'journal',
  year: 'year',
  impactFactor: 'impactFactor',
  abstract: 'abstract',
  fullText: 'fullText',
  source: 'source',
  oaUrl: 'oaUrl',
  createdAt: 'createdAt'
} as const

export type PaperScalarFieldEnum = (typeof PaperScalarFieldEnum)[keyof typeof PaperScalarFieldEnum]


export const ExtractionScalarFieldEnum = {
  id: 'id',
  paperId: 'paperId',
  drugName: 'drugName',
  drugConc: 'drugConc',
  cellLine: 'cellLine',
  pathway: 'pathway',
  pathwayDir: 'pathwayDir',
  phenotype: 'phenotype',
  phenotypeDir: 'phenotypeDir',
  method: 'method',
  conclusion: 'conclusion',
  rawText: 'rawText',
  confidence: 'confidence',
  verified: 'verified',
  createdAt: 'createdAt'
} as const

export type ExtractionScalarFieldEnum = (typeof ExtractionScalarFieldEnum)[keyof typeof ExtractionScalarFieldEnum]


export const HypothesisScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  statement: 'statement',
  status: 'status',
  evidence: 'evidence',
  basedOn: 'basedOn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type HypothesisScalarFieldEnum = (typeof HypothesisScalarFieldEnum)[keyof typeof HypothesisScalarFieldEnum]


export const ExperimentScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  hypothesisId: 'hypothesisId',
  name: 'name',
  type: 'type',
  status: 'status',
  protocol: 'protocol',
  variables: 'variables',
  result: 'result',
  troubleshoot: 'troubleshoot',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExperimentScalarFieldEnum = (typeof ExperimentScalarFieldEnum)[keyof typeof ExperimentScalarFieldEnum]


export const ExperimentDataScalarFieldEnum = {
  id: 'id',
  experimentId: 'experimentId',
  fileType: 'fileType',
  fileName: 'fileName',
  fileUrl: 'fileUrl',
  parsedData: 'parsedData',
  analysis: 'analysis',
  createdAt: 'createdAt'
} as const

export type ExperimentDataScalarFieldEnum = (typeof ExperimentDataScalarFieldEnum)[keyof typeof ExperimentDataScalarFieldEnum]


export const TimelineEventScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  type: 'type',
  title: 'title',
  content: 'content',
  metadata: 'metadata',
  sortOrder: 'sortOrder',
  weekNumber: 'weekNumber',
  createdAt: 'createdAt'
} as const

export type TimelineEventScalarFieldEnum = (typeof TimelineEventScalarFieldEnum)[keyof typeof TimelineEventScalarFieldEnum]


export const ManuscriptScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  journal: 'journal',
  language: 'language',
  abstract: 'abstract',
  introduction: 'introduction',
  methods: 'methods',
  results: 'results',
  discussion: 'discussion',
  references: 'references',
  reviewSimulation: 'reviewSimulation',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ManuscriptScalarFieldEnum = (typeof ManuscriptScalarFieldEnum)[keyof typeof ManuscriptScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

