
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model Paper
 * 
 */
export type Paper = Prisma.PaperModel
/**
 * Model Extraction
 * 
 */
export type Extraction = Prisma.ExtractionModel
/**
 * Model Hypothesis
 * 
 */
export type Hypothesis = Prisma.HypothesisModel
/**
 * Model Experiment
 * 
 */
export type Experiment = Prisma.ExperimentModel
/**
 * Model ExperimentData
 * 
 */
export type ExperimentData = Prisma.ExperimentDataModel
/**
 * Model TimelineEvent
 * 
 */
export type TimelineEvent = Prisma.TimelineEventModel
/**
 * Model Manuscript
 * 
 */
export type Manuscript = Prisma.ManuscriptModel
